#pragma once
#include "display.h"

#define display_neopixel_frame_id DISPLAY_NEOPIXEL_FRAME_ID
#define display_encoder_frame_id DISPLAY_ENCODER_FRAME_ID
#define display_neopixel_length DISPLAY_NEOPIXEL_LENGTH
#define display_encoder_length DISPLAY_ENCODER_LENGTH
#define display_neopixel_is_extended DISPLAY_NEOPIXEL_IS_EXTENDED
#define display_encoder_is_extended DISPLAY_ENCODER_IS_EXTENDED
#define display_neopixel_name DISPLAY_NEOPIXEL_NAME
#define display_encoder_name DISPLAY_ENCODER_NAME
#define display_neopixel_led_00_name DISPLAY_NEOPIXEL_LED_00_NAME
#define display_neopixel_led_01_name DISPLAY_NEOPIXEL_LED_01_NAME
#define display_neopixel_led_02_name DISPLAY_NEOPIXEL_LED_02_NAME
#define display_neopixel_led_03_name DISPLAY_NEOPIXEL_LED_03_NAME
#define display_neopixel_led_04_name DISPLAY_NEOPIXEL_LED_04_NAME
#define display_neopixel_led_05_name DISPLAY_NEOPIXEL_LED_05_NAME
#define display_neopixel_led_06_name DISPLAY_NEOPIXEL_LED_06_NAME
#define display_neopixel_led_07_name DISPLAY_NEOPIXEL_LED_07_NAME
#define display_neopixel_led_08_name DISPLAY_NEOPIXEL_LED_08_NAME
#define display_neopixel_led_09_name DISPLAY_NEOPIXEL_LED_09_NAME
#define display_neopixel_led_10_name DISPLAY_NEOPIXEL_LED_10_NAME
#define display_neopixel_led_11_name DISPLAY_NEOPIXEL_LED_11_NAME
#define display_neopixel_led_12_name DISPLAY_NEOPIXEL_LED_12_NAME
#define display_neopixel_led_13_name DISPLAY_NEOPIXEL_LED_13_NAME
#define display_neopixel_led_14_name DISPLAY_NEOPIXEL_LED_14_NAME
#define display_neopixel_led_15_name DISPLAY_NEOPIXEL_LED_15_NAME
#define display_neopixel_brightness_name DISPLAY_NEOPIXEL_BRIGHTNESS_NAME
#define display_encoder_rotary_dial_name DISPLAY_ENCODER_ROTARY_DIAL_NAME
#define display_encoder_button_name DISPLAY_ENCODER_BUTTON_NAME
