/**
 * @file display.h
 *
 * @brief This header file was generated by cantools version 41.1.1 Fri Apr 17 11:48:39 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef DISPLAY_H
#define DISPLAY_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define DISPLAY_NEOPIXEL_LEFT_FRAME_ID (0x1041u)
#define DISPLAY_NEOPIXEL_RIGHT_FRAME_ID (0x1042u)
#define DISPLAY_NEOPIXEL_FRAME_ID (0x1040u)

/* Frame lengths in bytes. */
#define DISPLAY_NEOPIXEL_LEFT_LENGTH (64u)
#define DISPLAY_NEOPIXEL_RIGHT_LENGTH (64u)
#define DISPLAY_NEOPIXEL_LENGTH (64u)

/* Extended or standard frame types. */
#define DISPLAY_NEOPIXEL_LEFT_IS_EXTENDED (1)
#define DISPLAY_NEOPIXEL_RIGHT_IS_EXTENDED (1)
#define DISPLAY_NEOPIXEL_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define DISPLAY_NEOPIXEL_LEFT_NAME "neopixel_left"
#define DISPLAY_NEOPIXEL_RIGHT_NAME "neopixel_right"
#define DISPLAY_NEOPIXEL_NAME "neopixel"

/* Signal Names. */
#define DISPLAY_NEOPIXEL_LEFT_BRIGHTNESS_NAME "brightness"
#define DISPLAY_NEOPIXEL_LEFT_LED_LEFT_0_NAME "led_left_0"
#define DISPLAY_NEOPIXEL_LEFT_LED_LEFT_1_NAME "led_left_1"
#define DISPLAY_NEOPIXEL_LEFT_LED_LEFT_2_NAME "led_left_2"
#define DISPLAY_NEOPIXEL_RIGHT_BRIGHTNESS_NAME "brightness"
#define DISPLAY_NEOPIXEL_RIGHT_LED_RIGHT_0_NAME "led_right_0"
#define DISPLAY_NEOPIXEL_RIGHT_LED_RIGHT_1_NAME "led_right_1"
#define DISPLAY_NEOPIXEL_RIGHT_LED_RIGHT_2_NAME "led_right_2"
#define DISPLAY_NEOPIXEL_BRIGHTNESS_NAME "brightness"
#define DISPLAY_NEOPIXEL_LED_00_NAME "led_00"
#define DISPLAY_NEOPIXEL_LED_01_NAME "led_01"
#define DISPLAY_NEOPIXEL_LED_02_NAME "led_02"
#define DISPLAY_NEOPIXEL_LED_03_NAME "led_03"
#define DISPLAY_NEOPIXEL_LED_04_NAME "led_04"
#define DISPLAY_NEOPIXEL_LED_05_NAME "led_05"
#define DISPLAY_NEOPIXEL_LED_06_NAME "led_06"
#define DISPLAY_NEOPIXEL_LED_07_NAME "led_07"
#define DISPLAY_NEOPIXEL_LED_08_NAME "led_08"
#define DISPLAY_NEOPIXEL_LED_09_NAME "led_09"
#define DISPLAY_NEOPIXEL_LED_10_NAME "led_10"
#define DISPLAY_NEOPIXEL_LED_11_NAME "led_11"
#define DISPLAY_NEOPIXEL_LED_12_NAME "led_12"
#define DISPLAY_NEOPIXEL_LED_13_NAME "led_13"
#define DISPLAY_NEOPIXEL_LED_14_NAME "led_14"

/**
 * Signals in message neopixel_left.
 *
 * All signal values are as on the CAN bus.
 */
struct display_neopixel_left_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t brightness;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_left_0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_left_1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_left_2;
};

/**
 * Signals in message neopixel_right.
 *
 * All signal values are as on the CAN bus.
 */
struct display_neopixel_right_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t brightness;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_right_0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_right_1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_right_2;
};

/**
 * Signals in message neopixel.
 *
 * All signal values are as on the CAN bus.
 */
struct display_neopixel_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t brightness;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_00;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_01;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_02;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_03;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_04;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_05;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_06;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_07;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_08;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_09;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_10;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_11;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_12;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_13;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t led_14;
};

/**
 * Pack message neopixel_left.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int display_neopixel_left_pack(
    uint8_t *dst_p,
    const struct display_neopixel_left_t *src_p,
    size_t size);

/**
 * Unpack message neopixel_left.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int display_neopixel_left_unpack(
    struct display_neopixel_left_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from neopixel_left.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int display_neopixel_left_init(struct display_neopixel_left_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t display_neopixel_left_brightness_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_left_brightness_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_left_brightness_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_left_led_left_0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_left_led_left_0_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_left_led_left_0_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_left_led_left_1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_left_led_left_1_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_left_led_left_1_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_left_led_left_2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_left_led_left_2_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_left_led_left_2_is_in_range(uint32_t value);

/**
 * Pack message neopixel_right.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int display_neopixel_right_pack(
    uint8_t *dst_p,
    const struct display_neopixel_right_t *src_p,
    size_t size);

/**
 * Unpack message neopixel_right.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int display_neopixel_right_unpack(
    struct display_neopixel_right_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from neopixel_right.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int display_neopixel_right_init(struct display_neopixel_right_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t display_neopixel_right_brightness_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_right_brightness_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_right_brightness_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_right_led_right_0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_right_led_right_0_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_right_led_right_0_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_right_led_right_1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_right_led_right_1_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_right_led_right_1_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_right_led_right_2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_right_led_right_2_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_right_led_right_2_is_in_range(uint32_t value);

/**
 * Pack message neopixel.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int display_neopixel_pack(
    uint8_t *dst_p,
    const struct display_neopixel_t *src_p,
    size_t size);

/**
 * Unpack message neopixel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int display_neopixel_unpack(
    struct display_neopixel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from neopixel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int display_neopixel_init(struct display_neopixel_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t display_neopixel_brightness_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_brightness_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_brightness_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_00_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_00_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_00_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_01_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_01_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_01_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_02_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_02_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_02_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_03_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_03_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_03_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_04_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_04_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_04_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_05_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_05_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_05_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_06_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_06_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_06_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_07_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_07_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_07_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_08_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_08_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_08_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_09_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_09_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_09_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_10_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_10_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_10_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_11_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_11_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_11_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_12_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_12_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_12_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_13_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_13_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_13_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t display_neopixel_led_14_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double display_neopixel_led_14_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool display_neopixel_led_14_is_in_range(uint32_t value);


#ifdef __cplusplus
}
#endif

#endif
