/**
 * @file izze_imu_v2.c
 *
 * @brief This source file was generated by cantools version 41.1.1 Sat Apr 18 15:39:07 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "izze_imu_v2.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int izze_imu_v2_angular_rate_rear_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_angular_rate_rear_t *src_p,
    size_t size)
{
    uint16_t angular_rate_x_axis;
    uint16_t angular_rate_y_axis;
    uint16_t angular_rate_z_axis;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    angular_rate_x_axis = (uint16_t)src_p->angular_rate_x_axis;
    dst_p[0] |= pack_right_shift_u16(angular_rate_x_axis, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(angular_rate_x_axis, 0u, 0xffu);
    angular_rate_y_axis = (uint16_t)src_p->angular_rate_y_axis;
    dst_p[2] |= pack_right_shift_u16(angular_rate_y_axis, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(angular_rate_y_axis, 0u, 0xffu);
    angular_rate_z_axis = (uint16_t)src_p->angular_rate_z_axis;
    dst_p[4] |= pack_right_shift_u16(angular_rate_z_axis, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(angular_rate_z_axis, 0u, 0xffu);

    return (8);
}

int izze_imu_v2_angular_rate_rear_unpack(
    struct izze_imu_v2_angular_rate_rear_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t angular_rate_x_axis;
    uint16_t angular_rate_y_axis;
    uint16_t angular_rate_z_axis;

    if (size < 8u) {
        return (-EINVAL);
    }

    angular_rate_x_axis = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    angular_rate_x_axis |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->angular_rate_x_axis = (int16_t)angular_rate_x_axis;
    angular_rate_y_axis = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    angular_rate_y_axis |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->angular_rate_y_axis = (int16_t)angular_rate_y_axis;
    angular_rate_z_axis = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    angular_rate_z_axis |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->angular_rate_z_axis = (int16_t)angular_rate_z_axis;

    return (0);
}

int izze_imu_v2_angular_rate_rear_init(struct izze_imu_v2_angular_rate_rear_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_imu_v2_angular_rate_rear_t));

    return 0;
}

int16_t izze_imu_v2_angular_rate_rear_angular_rate_x_axis_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_rear_angular_rate_x_axis_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_rear_angular_rate_x_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_imu_v2_angular_rate_rear_angular_rate_y_axis_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_rear_angular_rate_y_axis_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_rear_angular_rate_y_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_imu_v2_angular_rate_rear_angular_rate_z_axis_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_rear_angular_rate_z_axis_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_rear_angular_rate_z_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int izze_imu_v2_acceleration_rear_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_acceleration_rear_t *src_p,
    size_t size)
{
    uint16_t acceleration_x_axis;
    uint16_t acceleration_y_axis;
    uint16_t acceleration_z_axis;
    uint16_t imu_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    acceleration_x_axis = (uint16_t)src_p->acceleration_x_axis;
    dst_p[0] |= pack_right_shift_u16(acceleration_x_axis, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(acceleration_x_axis, 0u, 0xffu);
    acceleration_y_axis = (uint16_t)src_p->acceleration_y_axis;
    dst_p[2] |= pack_right_shift_u16(acceleration_y_axis, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(acceleration_y_axis, 0u, 0xffu);
    acceleration_z_axis = (uint16_t)src_p->acceleration_z_axis;
    dst_p[4] |= pack_right_shift_u16(acceleration_z_axis, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(acceleration_z_axis, 0u, 0xffu);
    imu_temp = (uint16_t)src_p->imu_temp;
    dst_p[6] |= pack_right_shift_u16(imu_temp, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(imu_temp, 0u, 0xffu);

    return (8);
}

int izze_imu_v2_acceleration_rear_unpack(
    struct izze_imu_v2_acceleration_rear_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acceleration_x_axis;
    uint16_t acceleration_y_axis;
    uint16_t acceleration_z_axis;
    uint16_t imu_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    acceleration_x_axis = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    acceleration_x_axis |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acceleration_x_axis = (int16_t)acceleration_x_axis;
    acceleration_y_axis = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    acceleration_y_axis |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acceleration_y_axis = (int16_t)acceleration_y_axis;
    acceleration_z_axis = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    acceleration_z_axis |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acceleration_z_axis = (int16_t)acceleration_z_axis;
    imu_temp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    imu_temp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->imu_temp = (int16_t)imu_temp;

    return (0);
}

int izze_imu_v2_acceleration_rear_init(struct izze_imu_v2_acceleration_rear_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_imu_v2_acceleration_rear_t));

    return 0;
}

int16_t izze_imu_v2_acceleration_rear_acceleration_x_axis_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_rear_acceleration_x_axis_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_rear_acceleration_x_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_imu_v2_acceleration_rear_acceleration_y_axis_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_rear_acceleration_y_axis_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_rear_acceleration_y_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_imu_v2_acceleration_rear_acceleration_z_axis_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_rear_acceleration_z_axis_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_rear_acceleration_z_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_imu_v2_acceleration_rear_imu_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_acceleration_rear_imu_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_acceleration_rear_imu_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int izze_imu_v2_acceleration_front_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_acceleration_front_t *src_p,
    size_t size)
{
    uint16_t acceleration_x_axis;
    uint16_t acceleration_y_axis;
    uint16_t acceleration_z_axis;
    uint16_t imu_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    acceleration_x_axis = (uint16_t)src_p->acceleration_x_axis;
    dst_p[0] |= pack_right_shift_u16(acceleration_x_axis, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(acceleration_x_axis, 0u, 0xffu);
    acceleration_y_axis = (uint16_t)src_p->acceleration_y_axis;
    dst_p[2] |= pack_right_shift_u16(acceleration_y_axis, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(acceleration_y_axis, 0u, 0xffu);
    acceleration_z_axis = (uint16_t)src_p->acceleration_z_axis;
    dst_p[4] |= pack_right_shift_u16(acceleration_z_axis, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(acceleration_z_axis, 0u, 0xffu);
    imu_temp = (uint16_t)src_p->imu_temp;
    dst_p[6] |= pack_right_shift_u16(imu_temp, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(imu_temp, 0u, 0xffu);

    return (8);
}

int izze_imu_v2_acceleration_front_unpack(
    struct izze_imu_v2_acceleration_front_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acceleration_x_axis;
    uint16_t acceleration_y_axis;
    uint16_t acceleration_z_axis;
    uint16_t imu_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    acceleration_x_axis = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    acceleration_x_axis |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acceleration_x_axis = (int16_t)acceleration_x_axis;
    acceleration_y_axis = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    acceleration_y_axis |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acceleration_y_axis = (int16_t)acceleration_y_axis;
    acceleration_z_axis = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    acceleration_z_axis |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acceleration_z_axis = (int16_t)acceleration_z_axis;
    imu_temp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    imu_temp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->imu_temp = (int16_t)imu_temp;

    return (0);
}

int izze_imu_v2_acceleration_front_init(struct izze_imu_v2_acceleration_front_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_imu_v2_acceleration_front_t));

    return 0;
}

int16_t izze_imu_v2_acceleration_front_acceleration_x_axis_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_front_acceleration_x_axis_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_front_acceleration_x_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_imu_v2_acceleration_front_acceleration_y_axis_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_front_acceleration_y_axis_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_front_acceleration_y_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_imu_v2_acceleration_front_acceleration_z_axis_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double izze_imu_v2_acceleration_front_acceleration_z_axis_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool izze_imu_v2_acceleration_front_acceleration_z_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_imu_v2_acceleration_front_imu_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_acceleration_front_imu_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_acceleration_front_imu_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int izze_imu_v2_angular_rate_front_pack(
    uint8_t *dst_p,
    const struct izze_imu_v2_angular_rate_front_t *src_p,
    size_t size)
{
    uint16_t angular_rate_x_axis;
    uint16_t angular_rate_y_axis;
    uint16_t angular_rate_z_axis;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    angular_rate_x_axis = (uint16_t)src_p->angular_rate_x_axis;
    dst_p[0] |= pack_right_shift_u16(angular_rate_x_axis, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(angular_rate_x_axis, 0u, 0xffu);
    angular_rate_y_axis = (uint16_t)src_p->angular_rate_y_axis;
    dst_p[2] |= pack_right_shift_u16(angular_rate_y_axis, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(angular_rate_y_axis, 0u, 0xffu);
    angular_rate_z_axis = (uint16_t)src_p->angular_rate_z_axis;
    dst_p[4] |= pack_right_shift_u16(angular_rate_z_axis, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(angular_rate_z_axis, 0u, 0xffu);

    return (8);
}

int izze_imu_v2_angular_rate_front_unpack(
    struct izze_imu_v2_angular_rate_front_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t angular_rate_x_axis;
    uint16_t angular_rate_y_axis;
    uint16_t angular_rate_z_axis;

    if (size < 8u) {
        return (-EINVAL);
    }

    angular_rate_x_axis = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    angular_rate_x_axis |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->angular_rate_x_axis = (int16_t)angular_rate_x_axis;
    angular_rate_y_axis = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    angular_rate_y_axis |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->angular_rate_y_axis = (int16_t)angular_rate_y_axis;
    angular_rate_z_axis = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    angular_rate_z_axis |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->angular_rate_z_axis = (int16_t)angular_rate_z_axis;

    return (0);
}

int izze_imu_v2_angular_rate_front_init(struct izze_imu_v2_angular_rate_front_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_imu_v2_angular_rate_front_t));

    return 0;
}

int16_t izze_imu_v2_angular_rate_front_angular_rate_x_axis_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_front_angular_rate_x_axis_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_front_angular_rate_x_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_imu_v2_angular_rate_front_angular_rate_y_axis_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_front_angular_rate_y_axis_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_front_angular_rate_y_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_imu_v2_angular_rate_front_angular_rate_z_axis_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double izze_imu_v2_angular_rate_front_angular_rate_z_axis_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool izze_imu_v2_angular_rate_front_angular_rate_z_axis_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
