#pragma once
#include "izze_imu_v2.h"

#define izze_imu_v2_h IZZE_IMU_V2_H
#define izze_imu_v2_angular_rate_rear_frame_id IZZE_IMU_V2_ANGULAR_RATE_REAR_FRAME_ID
#define izze_imu_v2_acceleration_rear_frame_id IZZE_IMU_V2_ACCELERATION_REAR_FRAME_ID
#define izze_imu_v2_acceleration_front_frame_id IZZE_IMU_V2_ACCELERATION_FRONT_FRAME_ID
#define izze_imu_v2_angular_rate_front_frame_id IZZE_IMU_V2_ANGULAR_RATE_FRONT_FRAME_ID
#define izze_imu_v2_angular_rate_rear_length IZZE_IMU_V2_ANGULAR_RATE_REAR_LENGTH
#define izze_imu_v2_acceleration_rear_length IZZE_IMU_V2_ACCELERATION_REAR_LENGTH
#define izze_imu_v2_acceleration_front_length IZZE_IMU_V2_ACCELERATION_FRONT_LENGTH
#define izze_imu_v2_angular_rate_front_length IZZE_IMU_V2_ANGULAR_RATE_FRONT_LENGTH
#define izze_imu_v2_angular_rate_rear_is_extended IZZE_IMU_V2_ANGULAR_RATE_REAR_IS_EXTENDED
#define izze_imu_v2_acceleration_rear_is_extended IZZE_IMU_V2_ACCELERATION_REAR_IS_EXTENDED
#define izze_imu_v2_acceleration_front_is_extended IZZE_IMU_V2_ACCELERATION_FRONT_IS_EXTENDED
#define izze_imu_v2_angular_rate_front_is_extended IZZE_IMU_V2_ANGULAR_RATE_FRONT_IS_EXTENDED
#define izze_imu_v2_angular_rate_rear_cycle_time_ms IZZE_IMU_V2_ANGULAR_RATE_REAR_CYCLE_TIME_MS
#define izze_imu_v2_acceleration_rear_cycle_time_ms IZZE_IMU_V2_ACCELERATION_REAR_CYCLE_TIME_MS
#define izze_imu_v2_acceleration_front_cycle_time_ms IZZE_IMU_V2_ACCELERATION_FRONT_CYCLE_TIME_MS
#define izze_imu_v2_angular_rate_front_cycle_time_ms IZZE_IMU_V2_ANGULAR_RATE_FRONT_CYCLE_TIME_MS
#define izze_imu_v2_angular_rate_rear_name IZZE_IMU_V2_ANGULAR_RATE_REAR_NAME
#define izze_imu_v2_acceleration_rear_name IZZE_IMU_V2_ACCELERATION_REAR_NAME
#define izze_imu_v2_acceleration_front_name IZZE_IMU_V2_ACCELERATION_FRONT_NAME
#define izze_imu_v2_angular_rate_front_name IZZE_IMU_V2_ANGULAR_RATE_FRONT_NAME
#define izze_imu_v2_angular_rate_rear_angular_rate_x_axis_name IZZE_IMU_V2_ANGULAR_RATE_REAR_ANGULAR_RATE_X_AXIS_NAME
#define izze_imu_v2_angular_rate_rear_angular_rate_y_axis_name IZZE_IMU_V2_ANGULAR_RATE_REAR_ANGULAR_RATE_Y_AXIS_NAME
#define izze_imu_v2_angular_rate_rear_angular_rate_z_axis_name IZZE_IMU_V2_ANGULAR_RATE_REAR_ANGULAR_RATE_Z_AXIS_NAME
#define izze_imu_v2_acceleration_rear_acceleration_x_axis_name IZZE_IMU_V2_ACCELERATION_REAR_ACCELERATION_X_AXIS_NAME
#define izze_imu_v2_acceleration_rear_acceleration_y_axis_name IZZE_IMU_V2_ACCELERATION_REAR_ACCELERATION_Y_AXIS_NAME
#define izze_imu_v2_acceleration_rear_acceleration_z_axis_name IZZE_IMU_V2_ACCELERATION_REAR_ACCELERATION_Z_AXIS_NAME
#define izze_imu_v2_acceleration_rear_imu_temp_name IZZE_IMU_V2_ACCELERATION_REAR_IMU_TEMP_NAME
#define izze_imu_v2_acceleration_front_acceleration_x_axis_name IZZE_IMU_V2_ACCELERATION_FRONT_ACCELERATION_X_AXIS_NAME
#define izze_imu_v2_acceleration_front_acceleration_y_axis_name IZZE_IMU_V2_ACCELERATION_FRONT_ACCELERATION_Y_AXIS_NAME
#define izze_imu_v2_acceleration_front_acceleration_z_axis_name IZZE_IMU_V2_ACCELERATION_FRONT_ACCELERATION_Z_AXIS_NAME
#define izze_imu_v2_acceleration_front_imu_temp_name IZZE_IMU_V2_ACCELERATION_FRONT_IMU_TEMP_NAME
#define izze_imu_v2_angular_rate_front_angular_rate_x_axis_name IZZE_IMU_V2_ANGULAR_RATE_FRONT_ANGULAR_RATE_X_AXIS_NAME
#define izze_imu_v2_angular_rate_front_angular_rate_y_axis_name IZZE_IMU_V2_ANGULAR_RATE_FRONT_ANGULAR_RATE_Y_AXIS_NAME
#define izze_imu_v2_angular_rate_front_angular_rate_z_axis_name IZZE_IMU_V2_ANGULAR_RATE_FRONT_ANGULAR_RATE_Z_AXIS_NAME
