/**
 * @file izze_ttpms.c
 *
 * @brief This source file was generated by cantools version 41.1.1 Fri Apr 17 11:15:51 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "izze_ttpms.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int izze_ttpms_rr_ttpms_6_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rr_ttpms_6_t *src_p,
    size_t size)
{
    uint16_t rr_ttpms_rssi;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rr_ttpms_tc, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rr_ttpms_tc, 0u, 0xffu);
    rr_ttpms_rssi = (uint16_t)src_p->rr_ttpms_rssi;
    dst_p[2] |= pack_right_shift_u16(rr_ttpms_rssi, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(rr_ttpms_rssi, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rr_ttpms_t, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rr_ttpms_t, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rr_ttpms_node_id, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rr_ttpms_node_id, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rr_ttpms_6_unpack(
    struct izze_ttpms_rr_ttpms_6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rr_ttpms_rssi;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_ttpms_tc = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rr_ttpms_tc |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    rr_ttpms_rssi = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    rr_ttpms_rssi |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rr_ttpms_rssi = (int16_t)rr_ttpms_rssi;
    dst_p->rr_ttpms_t = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rr_ttpms_t |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rr_ttpms_node_id = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rr_ttpms_node_id |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rr_ttpms_6_init(struct izze_ttpms_rr_ttpms_6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rr_ttpms_6_t));

    return 0;
}

uint16_t izze_ttpms_rr_ttpms_6_rr_ttpms_tc_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rr_ttpms_6_rr_ttpms_tc_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rr_ttpms_6_rr_ttpms_tc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_ttpms_rr_ttpms_6_rr_ttpms_rssi_encode(double value)
{
    return (int16_t)(value);
}

double izze_ttpms_rr_ttpms_6_rr_ttpms_rssi_decode(int16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rr_ttpms_6_rr_ttpms_rssi_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_6_rr_ttpms_t_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_6_rr_ttpms_t_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_6_rr_ttpms_t_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_6_rr_ttpms_node_id_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rr_ttpms_6_rr_ttpms_node_id_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rr_ttpms_6_rr_ttpms_node_id_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rr_ttpms_5_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rr_ttpms_5_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rr_ttpms_t13, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rr_ttpms_t13, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rr_ttpms_t14, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rr_ttpms_t14, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rr_ttpms_t15, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rr_ttpms_t15, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rr_ttpms_t16, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rr_ttpms_t16, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rr_ttpms_5_unpack(
    struct izze_ttpms_rr_ttpms_5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_ttpms_t13 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rr_ttpms_t13 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rr_ttpms_t14 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rr_ttpms_t14 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rr_ttpms_t15 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rr_ttpms_t15 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rr_ttpms_t16 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rr_ttpms_t16 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rr_ttpms_5_init(struct izze_ttpms_rr_ttpms_5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rr_ttpms_5_t));

    return 0;
}

uint16_t izze_ttpms_rr_ttpms_5_rr_ttpms_t13_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_5_rr_ttpms_t13_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_5_rr_ttpms_t13_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_5_rr_ttpms_t14_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_5_rr_ttpms_t14_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_5_rr_ttpms_t14_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_5_rr_ttpms_t15_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_5_rr_ttpms_t15_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_5_rr_ttpms_t15_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_5_rr_ttpms_t16_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_5_rr_ttpms_t16_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_5_rr_ttpms_t16_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rr_ttpms_4_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rr_ttpms_4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rr_ttpms_t9, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rr_ttpms_t9, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rr_ttpms_t10, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rr_ttpms_t10, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rr_ttpms_t11, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rr_ttpms_t11, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rr_ttpms_t12, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rr_ttpms_t12, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rr_ttpms_4_unpack(
    struct izze_ttpms_rr_ttpms_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_ttpms_t9 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rr_ttpms_t9 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rr_ttpms_t10 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rr_ttpms_t10 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rr_ttpms_t11 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rr_ttpms_t11 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rr_ttpms_t12 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rr_ttpms_t12 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rr_ttpms_4_init(struct izze_ttpms_rr_ttpms_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rr_ttpms_4_t));

    return 0;
}

uint16_t izze_ttpms_rr_ttpms_4_rr_ttpms_t9_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_4_rr_ttpms_t9_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_4_rr_ttpms_t9_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_4_rr_ttpms_t10_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_4_rr_ttpms_t10_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_4_rr_ttpms_t10_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_4_rr_ttpms_t11_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_4_rr_ttpms_t11_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_4_rr_ttpms_t11_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_4_rr_ttpms_t12_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_4_rr_ttpms_t12_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_4_rr_ttpms_t12_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rr_ttpms_3_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rr_ttpms_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rr_ttpms_t5, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rr_ttpms_t5, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rr_ttpms_t6, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rr_ttpms_t6, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rr_ttpms_t7, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rr_ttpms_t7, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rr_ttpms_t8, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rr_ttpms_t8, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rr_ttpms_3_unpack(
    struct izze_ttpms_rr_ttpms_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_ttpms_t5 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rr_ttpms_t5 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rr_ttpms_t6 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rr_ttpms_t6 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rr_ttpms_t7 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rr_ttpms_t7 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rr_ttpms_t8 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rr_ttpms_t8 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rr_ttpms_3_init(struct izze_ttpms_rr_ttpms_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rr_ttpms_3_t));

    return 0;
}

uint16_t izze_ttpms_rr_ttpms_3_rr_ttpms_t5_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_3_rr_ttpms_t5_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_3_rr_ttpms_t5_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_3_rr_ttpms_t6_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_3_rr_ttpms_t6_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_3_rr_ttpms_t6_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_3_rr_ttpms_t7_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_3_rr_ttpms_t7_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_3_rr_ttpms_t7_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_3_rr_ttpms_t8_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_3_rr_ttpms_t8_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_3_rr_ttpms_t8_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rr_ttpms_2_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rr_ttpms_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rr_ttpms_t1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rr_ttpms_t1, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rr_ttpms_t2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rr_ttpms_t2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rr_ttpms_t3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rr_ttpms_t3, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rr_ttpms_t4, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rr_ttpms_t4, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rr_ttpms_2_unpack(
    struct izze_ttpms_rr_ttpms_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_ttpms_t1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rr_ttpms_t1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rr_ttpms_t2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rr_ttpms_t2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rr_ttpms_t3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rr_ttpms_t3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rr_ttpms_t4 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rr_ttpms_t4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rr_ttpms_2_init(struct izze_ttpms_rr_ttpms_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rr_ttpms_2_t));

    return 0;
}

uint16_t izze_ttpms_rr_ttpms_2_rr_ttpms_t1_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_2_rr_ttpms_t1_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_2_rr_ttpms_t1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_2_rr_ttpms_t2_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_2_rr_ttpms_t2_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_2_rr_ttpms_t2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_2_rr_ttpms_t3_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_2_rr_ttpms_t3_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_2_rr_ttpms_t3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_2_rr_ttpms_t4_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rr_ttpms_2_rr_ttpms_t4_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rr_ttpms_2_rr_ttpms_t4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rr_ttpms_1_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rr_ttpms_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rr_ttpms_sn, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rr_ttpms_sn, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rr_ttpms_bat_v, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rr_ttpms_bat_v, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rr_ttpms_p, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rr_ttpms_p, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rr_ttpms_p_gauge, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rr_ttpms_p_gauge, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rr_ttpms_1_unpack(
    struct izze_ttpms_rr_ttpms_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_ttpms_sn = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rr_ttpms_sn |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rr_ttpms_bat_v = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rr_ttpms_bat_v |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rr_ttpms_p = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rr_ttpms_p |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rr_ttpms_p_gauge = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rr_ttpms_p_gauge |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rr_ttpms_1_init(struct izze_ttpms_rr_ttpms_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rr_ttpms_1_t));

    return 0;
}

uint16_t izze_ttpms_rr_ttpms_1_rr_ttpms_sn_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rr_ttpms_1_rr_ttpms_sn_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rr_ttpms_1_rr_ttpms_sn_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_1_rr_ttpms_bat_v_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rr_ttpms_1_rr_ttpms_bat_v_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rr_ttpms_1_rr_ttpms_bat_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_1_rr_ttpms_p_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rr_ttpms_1_rr_ttpms_p_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rr_ttpms_1_rr_ttpms_p_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rr_ttpms_1_rr_ttpms_p_gauge_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rr_ttpms_1_rr_ttpms_p_gauge_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rr_ttpms_1_rr_ttpms_p_gauge_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lr_ttpms_6_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lr_ttpms_6_t *src_p,
    size_t size)
{
    uint16_t lr_ttpms_rssi;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lr_ttpms_tc, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lr_ttpms_tc, 0u, 0xffu);
    lr_ttpms_rssi = (uint16_t)src_p->lr_ttpms_rssi;
    dst_p[2] |= pack_right_shift_u16(lr_ttpms_rssi, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(lr_ttpms_rssi, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lr_ttpms_t, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lr_ttpms_t, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lr_ttpms_node_id, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lr_ttpms_node_id, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lr_ttpms_6_unpack(
    struct izze_ttpms_lr_ttpms_6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t lr_ttpms_rssi;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lr_ttpms_tc = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lr_ttpms_tc |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    lr_ttpms_rssi = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    lr_ttpms_rssi |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lr_ttpms_rssi = (int16_t)lr_ttpms_rssi;
    dst_p->lr_ttpms_t = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lr_ttpms_t |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lr_ttpms_node_id = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lr_ttpms_node_id |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lr_ttpms_6_init(struct izze_ttpms_lr_ttpms_6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lr_ttpms_6_t));

    return 0;
}

uint16_t izze_ttpms_lr_ttpms_6_lr_ttpms_tc_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lr_ttpms_6_lr_ttpms_tc_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lr_ttpms_6_lr_ttpms_tc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_ttpms_lr_ttpms_6_lr_ttpms_rssi_encode(double value)
{
    return (int16_t)(value);
}

double izze_ttpms_lr_ttpms_6_lr_ttpms_rssi_decode(int16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lr_ttpms_6_lr_ttpms_rssi_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_6_lr_ttpms_t_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_6_lr_ttpms_t_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_6_lr_ttpms_t_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_6_lr_ttpms_node_id_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lr_ttpms_6_lr_ttpms_node_id_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lr_ttpms_6_lr_ttpms_node_id_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lr_ttpms_5_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lr_ttpms_5_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lr_ttpms_t13, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lr_ttpms_t13, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lr_ttpms_t14, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lr_ttpms_t14, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lr_ttpms_t15, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lr_ttpms_t15, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lr_ttpms_t16, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lr_ttpms_t16, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lr_ttpms_5_unpack(
    struct izze_ttpms_lr_ttpms_5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lr_ttpms_t13 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lr_ttpms_t13 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lr_ttpms_t14 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->lr_ttpms_t14 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lr_ttpms_t15 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lr_ttpms_t15 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lr_ttpms_t16 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lr_ttpms_t16 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lr_ttpms_5_init(struct izze_ttpms_lr_ttpms_5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lr_ttpms_5_t));

    return 0;
}

uint16_t izze_ttpms_lr_ttpms_5_lr_ttpms_t13_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_5_lr_ttpms_t13_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_5_lr_ttpms_t13_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_5_lr_ttpms_t14_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_5_lr_ttpms_t14_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_5_lr_ttpms_t14_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_5_lr_ttpms_t15_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_5_lr_ttpms_t15_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_5_lr_ttpms_t15_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_5_lr_ttpms_t16_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_5_lr_ttpms_t16_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_5_lr_ttpms_t16_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lr_ttpms_4_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lr_ttpms_4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lr_ttpms_t9, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lr_ttpms_t9, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lr_ttpms_t10, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lr_ttpms_t10, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lr_ttpms_t11, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lr_ttpms_t11, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lr_ttpms_t12, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lr_ttpms_t12, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lr_ttpms_4_unpack(
    struct izze_ttpms_lr_ttpms_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lr_ttpms_t9 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lr_ttpms_t9 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lr_ttpms_t10 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->lr_ttpms_t10 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lr_ttpms_t11 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lr_ttpms_t11 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lr_ttpms_t12 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lr_ttpms_t12 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lr_ttpms_4_init(struct izze_ttpms_lr_ttpms_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lr_ttpms_4_t));

    return 0;
}

uint16_t izze_ttpms_lr_ttpms_4_lr_ttpms_t9_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_4_lr_ttpms_t9_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_4_lr_ttpms_t9_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_4_lr_ttpms_t10_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_4_lr_ttpms_t10_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_4_lr_ttpms_t10_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_4_lr_ttpms_t11_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_4_lr_ttpms_t11_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_4_lr_ttpms_t11_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_4_lr_ttpms_t12_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_4_lr_ttpms_t12_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_4_lr_ttpms_t12_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lr_ttpms_3_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lr_ttpms_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lr_ttpms_t5, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lr_ttpms_t5, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lr_ttpms_t6, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lr_ttpms_t6, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lr_ttpms_t7, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lr_ttpms_t7, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lr_ttpms_t8, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lr_ttpms_t8, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lr_ttpms_3_unpack(
    struct izze_ttpms_lr_ttpms_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lr_ttpms_t5 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lr_ttpms_t5 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lr_ttpms_t6 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->lr_ttpms_t6 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lr_ttpms_t7 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lr_ttpms_t7 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lr_ttpms_t8 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lr_ttpms_t8 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lr_ttpms_3_init(struct izze_ttpms_lr_ttpms_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lr_ttpms_3_t));

    return 0;
}

uint16_t izze_ttpms_lr_ttpms_3_lr_ttpms_t5_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_3_lr_ttpms_t5_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_3_lr_ttpms_t5_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_3_lr_ttpms_t6_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_3_lr_ttpms_t6_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_3_lr_ttpms_t6_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_3_lr_ttpms_t7_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_3_lr_ttpms_t7_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_3_lr_ttpms_t7_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_3_lr_ttpms_t8_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_3_lr_ttpms_t8_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_3_lr_ttpms_t8_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lr_ttpms_2_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lr_ttpms_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lr_ttpms_t1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lr_ttpms_t1, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lr_ttpms_t2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lr_ttpms_t2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lr_ttpms_t3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lr_ttpms_t3, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lr_ttpms_t4, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lr_ttpms_t4, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lr_ttpms_2_unpack(
    struct izze_ttpms_lr_ttpms_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lr_ttpms_t1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lr_ttpms_t1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lr_ttpms_t2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->lr_ttpms_t2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lr_ttpms_t3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lr_ttpms_t3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lr_ttpms_t4 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lr_ttpms_t4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lr_ttpms_2_init(struct izze_ttpms_lr_ttpms_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lr_ttpms_2_t));

    return 0;
}

uint16_t izze_ttpms_lr_ttpms_2_lr_ttpms_t1_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_2_lr_ttpms_t1_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_2_lr_ttpms_t1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_2_lr_ttpms_t2_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_2_lr_ttpms_t2_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_2_lr_ttpms_t2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_2_lr_ttpms_t3_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_2_lr_ttpms_t3_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_2_lr_ttpms_t3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_2_lr_ttpms_t4_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lr_ttpms_2_lr_ttpms_t4_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lr_ttpms_2_lr_ttpms_t4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lr_ttpms_1_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lr_ttpms_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lr_ttpms_sn, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lr_ttpms_sn, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lr_ttpms_bat_v, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lr_ttpms_bat_v, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lr_ttpms_p, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lr_ttpms_p, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lr_ttpms_p_gauge, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lr_ttpms_p_gauge, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lr_ttpms_1_unpack(
    struct izze_ttpms_lr_ttpms_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lr_ttpms_sn = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lr_ttpms_sn |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lr_ttpms_bat_v = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->lr_ttpms_bat_v |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lr_ttpms_p = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lr_ttpms_p |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lr_ttpms_p_gauge = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lr_ttpms_p_gauge |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lr_ttpms_1_init(struct izze_ttpms_lr_ttpms_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lr_ttpms_1_t));

    return 0;
}

uint16_t izze_ttpms_lr_ttpms_1_lr_ttpms_sn_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lr_ttpms_1_lr_ttpms_sn_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lr_ttpms_1_lr_ttpms_sn_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_1_lr_ttpms_bat_v_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lr_ttpms_1_lr_ttpms_bat_v_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lr_ttpms_1_lr_ttpms_bat_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_1_lr_ttpms_p_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lr_ttpms_1_lr_ttpms_p_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lr_ttpms_1_lr_ttpms_p_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lr_ttpms_1_lr_ttpms_p_gauge_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lr_ttpms_1_lr_ttpms_p_gauge_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lr_ttpms_1_lr_ttpms_p_gauge_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rf_ttpms_6_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rf_ttpms_6_t *src_p,
    size_t size)
{
    uint16_t rf_ttpms_rssi;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rf_ttpms_tc, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rf_ttpms_tc, 0u, 0xffu);
    rf_ttpms_rssi = (uint16_t)src_p->rf_ttpms_rssi;
    dst_p[2] |= pack_right_shift_u16(rf_ttpms_rssi, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(rf_ttpms_rssi, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rf_ttpms_t, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rf_ttpms_t, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rf_ttpms_node_id, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rf_ttpms_node_id, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rf_ttpms_6_unpack(
    struct izze_ttpms_rf_ttpms_6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rf_ttpms_rssi;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rf_ttpms_tc = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rf_ttpms_tc |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    rf_ttpms_rssi = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    rf_ttpms_rssi |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rf_ttpms_rssi = (int16_t)rf_ttpms_rssi;
    dst_p->rf_ttpms_t = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rf_ttpms_t |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rf_ttpms_node_id = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rf_ttpms_node_id |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rf_ttpms_6_init(struct izze_ttpms_rf_ttpms_6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rf_ttpms_6_t));

    return 0;
}

uint16_t izze_ttpms_rf_ttpms_6_rf_ttpms_tc_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rf_ttpms_6_rf_ttpms_tc_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rf_ttpms_6_rf_ttpms_tc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_ttpms_rf_ttpms_6_rf_ttpms_rssi_encode(double value)
{
    return (int16_t)(value);
}

double izze_ttpms_rf_ttpms_6_rf_ttpms_rssi_decode(int16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rf_ttpms_6_rf_ttpms_rssi_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_6_rf_ttpms_t_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_6_rf_ttpms_t_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_6_rf_ttpms_t_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_6_rf_ttpms_node_id_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rf_ttpms_6_rf_ttpms_node_id_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rf_ttpms_6_rf_ttpms_node_id_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rf_ttpms_5_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rf_ttpms_5_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rf_ttpms_t13, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rf_ttpms_t13, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rf_ttpms_t14, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rf_ttpms_t14, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rf_ttpms_t15, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rf_ttpms_t15, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rf_ttpms_t16, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rf_ttpms_t16, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rf_ttpms_5_unpack(
    struct izze_ttpms_rf_ttpms_5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rf_ttpms_t13 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rf_ttpms_t13 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rf_ttpms_t14 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rf_ttpms_t14 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rf_ttpms_t15 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rf_ttpms_t15 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rf_ttpms_t16 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rf_ttpms_t16 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rf_ttpms_5_init(struct izze_ttpms_rf_ttpms_5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rf_ttpms_5_t));

    return 0;
}

uint16_t izze_ttpms_rf_ttpms_5_rf_ttpms_t13_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_5_rf_ttpms_t13_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_5_rf_ttpms_t13_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_5_rf_ttpms_t14_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_5_rf_ttpms_t14_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_5_rf_ttpms_t14_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_5_rf_ttpms_t15_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_5_rf_ttpms_t15_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_5_rf_ttpms_t15_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_5_rf_ttpms_t16_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_5_rf_ttpms_t16_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_5_rf_ttpms_t16_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rf_ttpms_4_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rf_ttpms_4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rf_ttpms_t9, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rf_ttpms_t9, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rf_ttpms_t10, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rf_ttpms_t10, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rf_ttpms_t11, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rf_ttpms_t11, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rf_ttpms_t12, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rf_ttpms_t12, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rf_ttpms_4_unpack(
    struct izze_ttpms_rf_ttpms_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rf_ttpms_t9 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rf_ttpms_t9 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rf_ttpms_t10 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rf_ttpms_t10 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rf_ttpms_t11 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rf_ttpms_t11 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rf_ttpms_t12 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rf_ttpms_t12 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rf_ttpms_4_init(struct izze_ttpms_rf_ttpms_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rf_ttpms_4_t));

    return 0;
}

uint16_t izze_ttpms_rf_ttpms_4_rf_ttpms_t9_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_4_rf_ttpms_t9_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_4_rf_ttpms_t9_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_4_rf_ttpms_t10_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_4_rf_ttpms_t10_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_4_rf_ttpms_t10_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_4_rf_ttpms_t11_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_4_rf_ttpms_t11_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_4_rf_ttpms_t11_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_4_rf_ttpms_t12_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_4_rf_ttpms_t12_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_4_rf_ttpms_t12_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rf_ttpms_3_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rf_ttpms_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rf_ttpms_t5, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rf_ttpms_t5, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rf_ttpms_t6, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rf_ttpms_t6, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rf_ttpms_t7, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rf_ttpms_t7, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rf_ttpms_t8, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rf_ttpms_t8, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rf_ttpms_3_unpack(
    struct izze_ttpms_rf_ttpms_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rf_ttpms_t5 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rf_ttpms_t5 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rf_ttpms_t6 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rf_ttpms_t6 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rf_ttpms_t7 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rf_ttpms_t7 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rf_ttpms_t8 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rf_ttpms_t8 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rf_ttpms_3_init(struct izze_ttpms_rf_ttpms_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rf_ttpms_3_t));

    return 0;
}

uint16_t izze_ttpms_rf_ttpms_3_rf_ttpms_t5_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_3_rf_ttpms_t5_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_3_rf_ttpms_t5_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_3_rf_ttpms_t6_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_3_rf_ttpms_t6_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_3_rf_ttpms_t6_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_3_rf_ttpms_t7_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_3_rf_ttpms_t7_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_3_rf_ttpms_t7_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_3_rf_ttpms_t8_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_3_rf_ttpms_t8_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_3_rf_ttpms_t8_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rf_ttpms_2_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rf_ttpms_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rf_ttpms_t1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rf_ttpms_t1, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rf_ttpms_t2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rf_ttpms_t2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rf_ttpms_t3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rf_ttpms_t3, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rf_ttpms_t4, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rf_ttpms_t4, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rf_ttpms_2_unpack(
    struct izze_ttpms_rf_ttpms_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rf_ttpms_t1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rf_ttpms_t1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rf_ttpms_t2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rf_ttpms_t2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rf_ttpms_t3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rf_ttpms_t3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rf_ttpms_t4 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rf_ttpms_t4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rf_ttpms_2_init(struct izze_ttpms_rf_ttpms_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rf_ttpms_2_t));

    return 0;
}

uint16_t izze_ttpms_rf_ttpms_2_rf_ttpms_t1_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_2_rf_ttpms_t1_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_2_rf_ttpms_t1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_2_rf_ttpms_t2_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_2_rf_ttpms_t2_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_2_rf_ttpms_t2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_2_rf_ttpms_t3_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_2_rf_ttpms_t3_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_2_rf_ttpms_t3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_2_rf_ttpms_t4_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_rf_ttpms_2_rf_ttpms_t4_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_rf_ttpms_2_rf_ttpms_t4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_rf_ttpms_1_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_rf_ttpms_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rf_ttpms_sn, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rf_ttpms_sn, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rf_ttpms_bat_v, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rf_ttpms_bat_v, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->rf_ttpms_p, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->rf_ttpms_p, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->rf_ttpms_p_gauge, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->rf_ttpms_p_gauge, 0u, 0xffu);

    return (8);
}

int izze_ttpms_rf_ttpms_1_unpack(
    struct izze_ttpms_rf_ttpms_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rf_ttpms_sn = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rf_ttpms_sn |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->rf_ttpms_bat_v = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rf_ttpms_bat_v |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->rf_ttpms_p = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->rf_ttpms_p |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->rf_ttpms_p_gauge = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->rf_ttpms_p_gauge |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_rf_ttpms_1_init(struct izze_ttpms_rf_ttpms_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_rf_ttpms_1_t));

    return 0;
}

uint16_t izze_ttpms_rf_ttpms_1_rf_ttpms_sn_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rf_ttpms_1_rf_ttpms_sn_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rf_ttpms_1_rf_ttpms_sn_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_1_rf_ttpms_bat_v_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rf_ttpms_1_rf_ttpms_bat_v_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rf_ttpms_1_rf_ttpms_bat_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_1_rf_ttpms_p_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rf_ttpms_1_rf_ttpms_p_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rf_ttpms_1_rf_ttpms_p_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_rf_ttpms_1_rf_ttpms_p_gauge_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_rf_ttpms_1_rf_ttpms_p_gauge_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_rf_ttpms_1_rf_ttpms_p_gauge_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lf_ttpms_6_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lf_ttpms_6_t *src_p,
    size_t size)
{
    uint16_t lf_ttpms_rssi;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lf_ttpms_tc, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lf_ttpms_tc, 0u, 0xffu);
    lf_ttpms_rssi = (uint16_t)src_p->lf_ttpms_rssi;
    dst_p[2] |= pack_right_shift_u16(lf_ttpms_rssi, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(lf_ttpms_rssi, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lf_ttpms_t, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lf_ttpms_t, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lf_ttpms_node_id, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lf_ttpms_node_id, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lf_ttpms_6_unpack(
    struct izze_ttpms_lf_ttpms_6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t lf_ttpms_rssi;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lf_ttpms_tc = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lf_ttpms_tc |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    lf_ttpms_rssi = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    lf_ttpms_rssi |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lf_ttpms_rssi = (int16_t)lf_ttpms_rssi;
    dst_p->lf_ttpms_t = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lf_ttpms_t |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lf_ttpms_node_id = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lf_ttpms_node_id |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lf_ttpms_6_init(struct izze_ttpms_lf_ttpms_6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lf_ttpms_6_t));

    return 0;
}

uint16_t izze_ttpms_lf_ttpms_6_lf_ttpms_tc_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lf_ttpms_6_lf_ttpms_tc_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lf_ttpms_6_lf_ttpms_tc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t izze_ttpms_lf_ttpms_6_lf_ttpms_rssi_encode(double value)
{
    return (int16_t)(value);
}

double izze_ttpms_lf_ttpms_6_lf_ttpms_rssi_decode(int16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lf_ttpms_6_lf_ttpms_rssi_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_6_lf_ttpms_t_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_6_lf_ttpms_t_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_6_lf_ttpms_t_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_6_lf_ttpms_node_id_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lf_ttpms_6_lf_ttpms_node_id_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lf_ttpms_6_lf_ttpms_node_id_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lf_ttpms_5_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lf_ttpms_5_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lf_ttpms_t13, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lf_ttpms_t13, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lf_ttpms_t14, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lf_ttpms_t14, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lf_ttpms_t15, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lf_ttpms_t15, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lf_ttpms_t16, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lf_ttpms_t16, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lf_ttpms_5_unpack(
    struct izze_ttpms_lf_ttpms_5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lf_ttpms_t13 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lf_ttpms_t13 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lf_ttpms_t14 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->lf_ttpms_t14 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lf_ttpms_t15 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lf_ttpms_t15 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lf_ttpms_t16 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lf_ttpms_t16 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lf_ttpms_5_init(struct izze_ttpms_lf_ttpms_5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lf_ttpms_5_t));

    return 0;
}

uint16_t izze_ttpms_lf_ttpms_5_lf_ttpms_t13_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_5_lf_ttpms_t13_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_5_lf_ttpms_t13_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_5_lf_ttpms_t14_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_5_lf_ttpms_t14_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_5_lf_ttpms_t14_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_5_lf_ttpms_t15_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_5_lf_ttpms_t15_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_5_lf_ttpms_t15_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_5_lf_ttpms_t16_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_5_lf_ttpms_t16_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_5_lf_ttpms_t16_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lf_ttpms_4_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lf_ttpms_4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lf_ttpms_t9, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lf_ttpms_t9, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lf_ttpms_t10, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lf_ttpms_t10, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lf_ttpms_t11, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lf_ttpms_t11, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lf_ttpms_t12, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lf_ttpms_t12, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lf_ttpms_4_unpack(
    struct izze_ttpms_lf_ttpms_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lf_ttpms_t9 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lf_ttpms_t9 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lf_ttpms_t10 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->lf_ttpms_t10 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lf_ttpms_t11 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lf_ttpms_t11 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lf_ttpms_t12 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lf_ttpms_t12 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lf_ttpms_4_init(struct izze_ttpms_lf_ttpms_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lf_ttpms_4_t));

    return 0;
}

uint16_t izze_ttpms_lf_ttpms_4_lf_ttpms_t9_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_4_lf_ttpms_t9_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_4_lf_ttpms_t9_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_4_lf_ttpms_t10_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_4_lf_ttpms_t10_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_4_lf_ttpms_t10_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_4_lf_ttpms_t11_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_4_lf_ttpms_t11_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_4_lf_ttpms_t11_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_4_lf_ttpms_t12_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_4_lf_ttpms_t12_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_4_lf_ttpms_t12_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lf_ttpms_3_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lf_ttpms_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lf_ttpms_t5, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lf_ttpms_t5, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lf_ttpms_t6, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lf_ttpms_t6, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lf_ttpms_t7, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lf_ttpms_t7, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lf_ttpms_t8, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lf_ttpms_t8, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lf_ttpms_3_unpack(
    struct izze_ttpms_lf_ttpms_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lf_ttpms_t5 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lf_ttpms_t5 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lf_ttpms_t6 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->lf_ttpms_t6 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lf_ttpms_t7 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lf_ttpms_t7 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lf_ttpms_t8 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lf_ttpms_t8 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lf_ttpms_3_init(struct izze_ttpms_lf_ttpms_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lf_ttpms_3_t));

    return 0;
}

uint16_t izze_ttpms_lf_ttpms_3_lf_ttpms_t5_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_3_lf_ttpms_t5_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_3_lf_ttpms_t5_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_3_lf_ttpms_t6_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_3_lf_ttpms_t6_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_3_lf_ttpms_t6_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_3_lf_ttpms_t7_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_3_lf_ttpms_t7_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_3_lf_ttpms_t7_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_3_lf_ttpms_t8_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_3_lf_ttpms_t8_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_3_lf_ttpms_t8_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lf_ttpms_2_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lf_ttpms_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lf_ttpms_t1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lf_ttpms_t1, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lf_ttpms_t2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lf_ttpms_t2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lf_ttpms_t3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lf_ttpms_t3, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lf_ttpms_t4, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lf_ttpms_t4, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lf_ttpms_2_unpack(
    struct izze_ttpms_lf_ttpms_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lf_ttpms_t1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lf_ttpms_t1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lf_ttpms_t2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->lf_ttpms_t2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lf_ttpms_t3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lf_ttpms_t3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lf_ttpms_t4 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lf_ttpms_t4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lf_ttpms_2_init(struct izze_ttpms_lf_ttpms_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lf_ttpms_2_t));

    return 0;
}

uint16_t izze_ttpms_lf_ttpms_2_lf_ttpms_t1_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_2_lf_ttpms_t1_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_2_lf_ttpms_t1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_2_lf_ttpms_t2_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_2_lf_ttpms_t2_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_2_lf_ttpms_t2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_2_lf_ttpms_t3_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_2_lf_ttpms_t3_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_2_lf_ttpms_t3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_2_lf_ttpms_t4_encode(double value)
{
    return (uint16_t)((value - -100.0) / 0.1);
}

double izze_ttpms_lf_ttpms_2_lf_ttpms_t4_decode(uint16_t value)
{
    return (((double)value * 0.1) + -100.0);
}

bool izze_ttpms_lf_ttpms_2_lf_ttpms_t4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int izze_ttpms_lf_ttpms_1_pack(
    uint8_t *dst_p,
    const struct izze_ttpms_lf_ttpms_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->lf_ttpms_sn, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->lf_ttpms_sn, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->lf_ttpms_bat_v, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lf_ttpms_bat_v, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lf_ttpms_p, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lf_ttpms_p, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lf_ttpms_p_gauge, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->lf_ttpms_p_gauge, 0u, 0xffu);

    return (8);
}

int izze_ttpms_lf_ttpms_1_unpack(
    struct izze_ttpms_lf_ttpms_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lf_ttpms_sn = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->lf_ttpms_sn |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->lf_ttpms_bat_v = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->lf_ttpms_bat_v |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lf_ttpms_p = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lf_ttpms_p |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lf_ttpms_p_gauge = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->lf_ttpms_p_gauge |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int izze_ttpms_lf_ttpms_1_init(struct izze_ttpms_lf_ttpms_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct izze_ttpms_lf_ttpms_1_t));

    return 0;
}

uint16_t izze_ttpms_lf_ttpms_1_lf_ttpms_sn_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lf_ttpms_1_lf_ttpms_sn_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lf_ttpms_1_lf_ttpms_sn_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_1_lf_ttpms_bat_v_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lf_ttpms_1_lf_ttpms_bat_v_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lf_ttpms_1_lf_ttpms_bat_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_1_lf_ttpms_p_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lf_ttpms_1_lf_ttpms_p_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lf_ttpms_1_lf_ttpms_p_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t izze_ttpms_lf_ttpms_1_lf_ttpms_p_gauge_encode(double value)
{
    return (uint16_t)(value);
}

double izze_ttpms_lf_ttpms_1_lf_ttpms_p_gauge_decode(uint16_t value)
{
    return ((double)value);
}

bool izze_ttpms_lf_ttpms_1_lf_ttpms_p_gauge_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
