/**
 * @file izze_irts_tire_v2.h
 *
 * @brief This header file was generated by cantools version 41.1.1 Fri Apr 17 12:04:01 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef IZZE_IRTS_TIRE_V2_H
#define IZZE_IRTS_TIRE_V2_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_1_FRAME_ID (0x4b0u)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_2_FRAME_ID (0x4b1u)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_3_FRAME_ID (0x4b2u)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_4_FRAME_ID (0x4b3u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_1_FRAME_ID (0x4b4u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_2_FRAME_ID (0x4b5u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_3_FRAME_ID (0x4b6u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_4_FRAME_ID (0x4b7u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_1_FRAME_ID (0x4b8u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_2_FRAME_ID (0x4b9u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_3_FRAME_ID (0x4bau)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_4_FRAME_ID (0x4bbu)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_1_FRAME_ID (0x4bcu)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_2_FRAME_ID (0x4bdu)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_3_FRAME_ID (0x4beu)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_4_FRAME_ID (0x4bfu)

/* Frame lengths in bytes. */
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_1_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_2_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_3_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_4_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_1_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_2_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_3_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_4_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_1_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_2_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_3_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_4_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_1_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_2_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_3_LENGTH (8u)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_4_LENGTH (8u)

/* Extended or standard frame types. */
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_1_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_2_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_3_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_4_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_1_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_2_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_3_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_4_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_1_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_2_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_3_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_4_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_1_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_2_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_3_IS_EXTENDED (0)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_4_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_1_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_2_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_3_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_4_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_1_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_2_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_3_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_4_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_1_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_2_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_3_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_4_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_1_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_2_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_3_CYCLE_TIME_MS (32u)
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_4_CYCLE_TIME_MS (32u)

/* Signal choices. */


/* Frame Names. */
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_1_NAME "LF_IRTS_Tire_1"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_2_NAME "LF_IRTS_Tire_2"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_3_NAME "LF_IRTS_Tire_3"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_4_NAME "LF_IRTS_Tire_4"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_1_NAME "RF_IRTS_Tire_1"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_2_NAME "RF_IRTS_Tire_2"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_3_NAME "RF_IRTS_Tire_3"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_4_NAME "RF_IRTS_Tire_4"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_1_NAME "LR_IRTS_Tire_1"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_2_NAME "LR_IRTS_Tire_2"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_3_NAME "LR_IRTS_Tire_3"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_4_NAME "LR_IRTS_Tire_4"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_1_NAME "RR_IRTS_Tire_1"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_2_NAME "RR_IRTS_Tire_2"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_3_NAME "RR_IRTS_Tire_3"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_4_NAME "RR_IRTS_Tire_4"

/* Signal Names. */
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_1_LF_TIRE_TEMP_01_NAME "LF_Tire_Temp_01"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_1_LF_TIRE_TEMP_02_NAME "LF_Tire_Temp_02"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_1_LF_TIRE_TEMP_03_NAME "LF_Tire_Temp_03"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_1_LF_TIRE_TEMP_04_NAME "LF_Tire_Temp_04"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_2_LF_TIRE_TEMP_05_NAME "LF_Tire_Temp_05"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_2_LF_TIRE_TEMP_06_NAME "LF_Tire_Temp_06"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_2_LF_TIRE_TEMP_07_NAME "LF_Tire_Temp_07"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_2_LF_TIRE_TEMP_08_NAME "LF_Tire_Temp_08"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_3_LF_TIRE_TEMP_09_NAME "LF_Tire_Temp_09"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_3_LF_TIRE_TEMP_10_NAME "LF_Tire_Temp_10"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_3_LF_TIRE_TEMP_11_NAME "LF_Tire_Temp_11"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_3_LF_TIRE_TEMP_12_NAME "LF_Tire_Temp_12"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_4_LF_TIRE_TEMP_13_NAME "LF_Tire_Temp_13"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_4_LF_TIRE_TEMP_14_NAME "LF_Tire_Temp_14"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_4_LF_TIRE_TEMP_15_NAME "LF_Tire_Temp_15"
#define IZZE_IRTS_TIRE_V2_LF_IRTS_TIRE_4_LF_TIRE_TEMP_16_NAME "LF_Tire_Temp_16"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_1_RF_TIRE_TEMP_01_NAME "RF_Tire_Temp_01"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_1_RF_TIRE_TEMP_02_NAME "RF_Tire_Temp_02"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_1_RF_TIRE_TEMP_03_NAME "RF_Tire_Temp_03"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_1_RF_TIRE_TEMP_04_NAME "RF_Tire_Temp_04"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_2_RF_TIRE_TEMP_05_NAME "RF_Tire_Temp_05"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_2_RF_TIRE_TEMP_06_NAME "RF_Tire_Temp_06"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_2_RF_TIRE_TEMP_07_NAME "RF_Tire_Temp_07"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_2_RF_TIRE_TEMP_08_NAME "RF_Tire_Temp_08"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_3_RF_TIRE_TEMP_09_NAME "RF_Tire_Temp_09"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_3_RF_TIRE_TEMP_10_NAME "RF_Tire_Temp_10"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_3_RF_TIRE_TEMP_11_NAME "RF_Tire_Temp_11"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_3_RF_TIRE_TEMP_12_NAME "RF_Tire_Temp_12"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_4_RF_TIRE_TEMP_13_NAME "RF_Tire_Temp_13"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_4_RF_TIRE_TEMP_14_NAME "RF_Tire_Temp_14"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_4_RF_TIRE_TEMP_15_NAME "RF_Tire_Temp_15"
#define IZZE_IRTS_TIRE_V2_RF_IRTS_TIRE_4_RF_TIRE_TEMP_16_NAME "RF_Tire_Temp_16"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_1_LR_TIRE_TEMP_01_NAME "LR_Tire_Temp_01"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_1_LR_TIRE_TEMP_02_NAME "LR_Tire_Temp_02"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_1_LR_TIRE_TEMP_03_NAME "LR_Tire_Temp_03"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_1_LR_TIRE_TEMP_04_NAME "LR_Tire_Temp_04"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_2_LR_TIRE_TEMP_05_NAME "LR_Tire_Temp_05"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_2_LR_TIRE_TEMP_06_NAME "LR_Tire_Temp_06"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_2_LR_TIRE_TEMP_07_NAME "LR_Tire_Temp_07"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_2_LR_TIRE_TEMP_08_NAME "LR_Tire_Temp_08"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_3_LR_TIRE_TEMP_09_NAME "LR_Tire_Temp_09"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_3_LR_TIRE_TEMP_10_NAME "LR_Tire_Temp_10"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_3_LR_TIRE_TEMP_11_NAME "LR_Tire_Temp_11"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_3_LR_TIRE_TEMP_12_NAME "LR_Tire_Temp_12"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_4_LR_TIRE_TEMP_13_NAME "LR_Tire_Temp_13"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_4_LR_TIRE_TEMP_14_NAME "LR_Tire_Temp_14"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_4_LR_TIRE_TEMP_15_NAME "LR_Tire_Temp_15"
#define IZZE_IRTS_TIRE_V2_LR_IRTS_TIRE_4_LR_TIRE_TEMP_16_NAME "LR_Tire_Temp_16"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_1_RR_TIRE_TEMP_01_NAME "RR_Tire_Temp_01"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_1_RR_TIRE_TEMP_02_NAME "RR_Tire_Temp_02"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_1_RR_TIRE_TEMP_03_NAME "RR_Tire_Temp_03"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_1_RR_TIRE_TEMP_04_NAME "RR_Tire_Temp_04"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_2_RR_TIRE_TEMP_05_NAME "RR_Tire_Temp_05"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_2_RR_TIRE_TEMP_06_NAME "RR_Tire_Temp_06"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_2_RR_TIRE_TEMP_07_NAME "RR_Tire_Temp_07"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_2_RR_TIRE_TEMP_08_NAME "RR_Tire_Temp_08"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_3_RR_TIRE_TEMP_09_NAME "RR_Tire_Temp_09"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_3_RR_TIRE_TEMP_10_NAME "RR_Tire_Temp_10"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_3_RR_TIRE_TEMP_11_NAME "RR_Tire_Temp_11"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_3_RR_TIRE_TEMP_12_NAME "RR_Tire_Temp_12"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_4_RR_TIRE_TEMP_13_NAME "RR_Tire_Temp_13"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_4_RR_TIRE_TEMP_14_NAME "RR_Tire_Temp_14"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_4_RR_TIRE_TEMP_15_NAME "RR_Tire_Temp_15"
#define IZZE_IRTS_TIRE_V2_RR_IRTS_TIRE_4_RR_TIRE_TEMP_16_NAME "RR_Tire_Temp_16"

/**
 * Signals in message LF_IRTS_Tire_1.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_lf_irts_tire_1_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_01;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_02;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_03;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_04;
};

/**
 * Signals in message LF_IRTS_Tire_2.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_lf_irts_tire_2_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_05;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_06;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_07;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_08;
};

/**
 * Signals in message LF_IRTS_Tire_3.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_lf_irts_tire_3_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_09;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_10;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_11;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_12;
};

/**
 * Signals in message LF_IRTS_Tire_4.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_lf_irts_tire_4_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_13;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_14;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_15;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lf_tire_temp_16;
};

/**
 * Signals in message RF_IRTS_Tire_1.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_rf_irts_tire_1_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_01;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_02;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_03;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_04;
};

/**
 * Signals in message RF_IRTS_Tire_2.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_rf_irts_tire_2_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_05;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_06;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_07;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_08;
};

/**
 * Signals in message RF_IRTS_Tire_3.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_rf_irts_tire_3_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_09;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_10;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_11;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_12;
};

/**
 * Signals in message RF_IRTS_Tire_4.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_rf_irts_tire_4_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_13;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_14;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_15;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rf_tire_temp_16;
};

/**
 * Signals in message LR_IRTS_Tire_1.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_lr_irts_tire_1_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_01;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_02;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_03;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_04;
};

/**
 * Signals in message LR_IRTS_Tire_2.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_lr_irts_tire_2_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_05;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_06;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_07;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_08;
};

/**
 * Signals in message LR_IRTS_Tire_3.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_lr_irts_tire_3_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_09;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_10;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_11;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_12;
};

/**
 * Signals in message LR_IRTS_Tire_4.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_lr_irts_tire_4_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_13;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_14;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_15;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t lr_tire_temp_16;
};

/**
 * Signals in message RR_IRTS_Tire_1.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_rr_irts_tire_1_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_01;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_02;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_03;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_04;
};

/**
 * Signals in message RR_IRTS_Tire_2.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_rr_irts_tire_2_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_05;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_06;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_07;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_08;
};

/**
 * Signals in message RR_IRTS_Tire_3.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_rr_irts_tire_3_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_09;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_10;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_11;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_12;
};

/**
 * Signals in message RR_IRTS_Tire_4.
 *
 * All signal values are as on the CAN bus.
 */
struct izze_irts_tire_v2_rr_irts_tire_4_t {
    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_13;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_14;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_15;

    /**
     * Range: 0..65535 (-100..6453.5 °C)
     * Scale: 0.1
     * Offset: -100
     */
    uint16_t rr_tire_temp_16;
};

/**
 * Pack message LF_IRTS_Tire_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_lf_irts_tire_1_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_lf_irts_tire_1_t *src_p,
    size_t size);

/**
 * Unpack message LF_IRTS_Tire_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_lf_irts_tire_1_unpack(
    struct izze_irts_tire_v2_lf_irts_tire_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LF_IRTS_Tire_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_lf_irts_tire_1_init(struct izze_irts_tire_v2_lf_irts_tire_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_01_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_01_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_01_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_02_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_02_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_02_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_03_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_03_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_03_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_04_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_04_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_1_lf_tire_temp_04_is_in_range(uint16_t value);

/**
 * Pack message LF_IRTS_Tire_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_lf_irts_tire_2_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_lf_irts_tire_2_t *src_p,
    size_t size);

/**
 * Unpack message LF_IRTS_Tire_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_lf_irts_tire_2_unpack(
    struct izze_irts_tire_v2_lf_irts_tire_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LF_IRTS_Tire_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_lf_irts_tire_2_init(struct izze_irts_tire_v2_lf_irts_tire_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_05_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_05_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_05_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_06_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_06_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_06_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_07_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_07_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_07_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_08_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_08_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_2_lf_tire_temp_08_is_in_range(uint16_t value);

/**
 * Pack message LF_IRTS_Tire_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_lf_irts_tire_3_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_lf_irts_tire_3_t *src_p,
    size_t size);

/**
 * Unpack message LF_IRTS_Tire_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_lf_irts_tire_3_unpack(
    struct izze_irts_tire_v2_lf_irts_tire_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LF_IRTS_Tire_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_lf_irts_tire_3_init(struct izze_irts_tire_v2_lf_irts_tire_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_09_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_09_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_09_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_10_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_10_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_10_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_11_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_11_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_11_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_12_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_12_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_3_lf_tire_temp_12_is_in_range(uint16_t value);

/**
 * Pack message LF_IRTS_Tire_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_lf_irts_tire_4_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_lf_irts_tire_4_t *src_p,
    size_t size);

/**
 * Unpack message LF_IRTS_Tire_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_lf_irts_tire_4_unpack(
    struct izze_irts_tire_v2_lf_irts_tire_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LF_IRTS_Tire_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_lf_irts_tire_4_init(struct izze_irts_tire_v2_lf_irts_tire_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_13_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_13_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_13_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_14_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_14_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_14_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_15_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_15_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_15_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_16_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_16_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lf_irts_tire_4_lf_tire_temp_16_is_in_range(uint16_t value);

/**
 * Pack message RF_IRTS_Tire_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_rf_irts_tire_1_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_rf_irts_tire_1_t *src_p,
    size_t size);

/**
 * Unpack message RF_IRTS_Tire_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_rf_irts_tire_1_unpack(
    struct izze_irts_tire_v2_rf_irts_tire_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RF_IRTS_Tire_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_rf_irts_tire_1_init(struct izze_irts_tire_v2_rf_irts_tire_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_01_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_01_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_01_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_02_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_02_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_02_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_03_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_03_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_03_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_04_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_04_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_1_rf_tire_temp_04_is_in_range(uint16_t value);

/**
 * Pack message RF_IRTS_Tire_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_rf_irts_tire_2_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_rf_irts_tire_2_t *src_p,
    size_t size);

/**
 * Unpack message RF_IRTS_Tire_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_rf_irts_tire_2_unpack(
    struct izze_irts_tire_v2_rf_irts_tire_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RF_IRTS_Tire_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_rf_irts_tire_2_init(struct izze_irts_tire_v2_rf_irts_tire_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_05_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_05_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_05_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_06_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_06_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_06_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_07_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_07_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_07_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_08_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_08_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_2_rf_tire_temp_08_is_in_range(uint16_t value);

/**
 * Pack message RF_IRTS_Tire_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_rf_irts_tire_3_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_rf_irts_tire_3_t *src_p,
    size_t size);

/**
 * Unpack message RF_IRTS_Tire_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_rf_irts_tire_3_unpack(
    struct izze_irts_tire_v2_rf_irts_tire_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RF_IRTS_Tire_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_rf_irts_tire_3_init(struct izze_irts_tire_v2_rf_irts_tire_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_09_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_09_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_09_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_10_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_10_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_10_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_11_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_11_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_11_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_12_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_12_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_3_rf_tire_temp_12_is_in_range(uint16_t value);

/**
 * Pack message RF_IRTS_Tire_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_rf_irts_tire_4_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_rf_irts_tire_4_t *src_p,
    size_t size);

/**
 * Unpack message RF_IRTS_Tire_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_rf_irts_tire_4_unpack(
    struct izze_irts_tire_v2_rf_irts_tire_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RF_IRTS_Tire_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_rf_irts_tire_4_init(struct izze_irts_tire_v2_rf_irts_tire_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_13_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_13_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_13_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_14_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_14_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_14_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_15_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_15_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_15_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_16_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_16_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rf_irts_tire_4_rf_tire_temp_16_is_in_range(uint16_t value);

/**
 * Pack message LR_IRTS_Tire_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_lr_irts_tire_1_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_lr_irts_tire_1_t *src_p,
    size_t size);

/**
 * Unpack message LR_IRTS_Tire_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_lr_irts_tire_1_unpack(
    struct izze_irts_tire_v2_lr_irts_tire_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LR_IRTS_Tire_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_lr_irts_tire_1_init(struct izze_irts_tire_v2_lr_irts_tire_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_01_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_01_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_01_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_02_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_02_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_02_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_03_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_03_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_03_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_04_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_04_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_1_lr_tire_temp_04_is_in_range(uint16_t value);

/**
 * Pack message LR_IRTS_Tire_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_lr_irts_tire_2_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_lr_irts_tire_2_t *src_p,
    size_t size);

/**
 * Unpack message LR_IRTS_Tire_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_lr_irts_tire_2_unpack(
    struct izze_irts_tire_v2_lr_irts_tire_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LR_IRTS_Tire_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_lr_irts_tire_2_init(struct izze_irts_tire_v2_lr_irts_tire_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_05_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_05_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_05_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_06_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_06_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_06_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_07_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_07_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_07_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_08_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_08_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_2_lr_tire_temp_08_is_in_range(uint16_t value);

/**
 * Pack message LR_IRTS_Tire_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_lr_irts_tire_3_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_lr_irts_tire_3_t *src_p,
    size_t size);

/**
 * Unpack message LR_IRTS_Tire_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_lr_irts_tire_3_unpack(
    struct izze_irts_tire_v2_lr_irts_tire_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LR_IRTS_Tire_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_lr_irts_tire_3_init(struct izze_irts_tire_v2_lr_irts_tire_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_09_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_09_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_09_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_10_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_10_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_10_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_11_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_11_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_11_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_12_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_12_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_3_lr_tire_temp_12_is_in_range(uint16_t value);

/**
 * Pack message LR_IRTS_Tire_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_lr_irts_tire_4_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_lr_irts_tire_4_t *src_p,
    size_t size);

/**
 * Unpack message LR_IRTS_Tire_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_lr_irts_tire_4_unpack(
    struct izze_irts_tire_v2_lr_irts_tire_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LR_IRTS_Tire_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_lr_irts_tire_4_init(struct izze_irts_tire_v2_lr_irts_tire_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_13_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_13_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_13_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_14_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_14_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_14_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_15_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_15_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_15_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_16_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_16_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_lr_irts_tire_4_lr_tire_temp_16_is_in_range(uint16_t value);

/**
 * Pack message RR_IRTS_Tire_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_rr_irts_tire_1_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_rr_irts_tire_1_t *src_p,
    size_t size);

/**
 * Unpack message RR_IRTS_Tire_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_rr_irts_tire_1_unpack(
    struct izze_irts_tire_v2_rr_irts_tire_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RR_IRTS_Tire_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_rr_irts_tire_1_init(struct izze_irts_tire_v2_rr_irts_tire_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_01_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_01_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_01_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_02_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_02_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_02_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_03_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_03_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_03_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_04_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_04_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_1_rr_tire_temp_04_is_in_range(uint16_t value);

/**
 * Pack message RR_IRTS_Tire_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_rr_irts_tire_2_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_rr_irts_tire_2_t *src_p,
    size_t size);

/**
 * Unpack message RR_IRTS_Tire_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_rr_irts_tire_2_unpack(
    struct izze_irts_tire_v2_rr_irts_tire_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RR_IRTS_Tire_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_rr_irts_tire_2_init(struct izze_irts_tire_v2_rr_irts_tire_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_05_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_05_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_05_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_06_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_06_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_06_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_07_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_07_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_07_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_08_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_08_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_2_rr_tire_temp_08_is_in_range(uint16_t value);

/**
 * Pack message RR_IRTS_Tire_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_rr_irts_tire_3_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_rr_irts_tire_3_t *src_p,
    size_t size);

/**
 * Unpack message RR_IRTS_Tire_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_rr_irts_tire_3_unpack(
    struct izze_irts_tire_v2_rr_irts_tire_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RR_IRTS_Tire_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_rr_irts_tire_3_init(struct izze_irts_tire_v2_rr_irts_tire_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_09_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_09_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_09_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_10_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_10_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_10_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_11_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_11_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_11_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_12_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_12_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_3_rr_tire_temp_12_is_in_range(uint16_t value);

/**
 * Pack message RR_IRTS_Tire_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int izze_irts_tire_v2_rr_irts_tire_4_pack(
    uint8_t *dst_p,
    const struct izze_irts_tire_v2_rr_irts_tire_4_t *src_p,
    size_t size);

/**
 * Unpack message RR_IRTS_Tire_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int izze_irts_tire_v2_rr_irts_tire_4_unpack(
    struct izze_irts_tire_v2_rr_irts_tire_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RR_IRTS_Tire_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int izze_irts_tire_v2_rr_irts_tire_4_init(struct izze_irts_tire_v2_rr_irts_tire_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_13_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_13_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_13_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_14_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_14_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_14_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_15_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_15_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_15_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_16_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_16_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool izze_irts_tire_v2_rr_irts_tire_4_rr_tire_temp_16_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
