/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 40.0.0 Mon Jul 21 11:00:03 2025.
 */

#include <string.h>

#include "swc.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int swc_buttons_pack(
    uint8_t *dst_p,
    const struct swc_buttons_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->shift_direction, 6u, 0xc0u);

    return (1);
}

int swc_buttons_unpack(
    struct swc_buttons_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->shift_direction = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);

    return (0);
}

int swc_buttons_init(struct swc_buttons_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct swc_buttons_t));

    return 0;
}

uint8_t swc_buttons_shift_direction_encode(double value)
{
    return (uint8_t)(value);
}

double swc_buttons_shift_direction_decode(uint8_t value)
{
    return ((double)value);
}

bool swc_buttons_shift_direction_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int swc_clutch_pack(
    uint8_t *dst_p,
    const struct swc_clutch_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_right_shift_u16(src_p->clutch_left, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->clutch_left, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->clutch_right, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->clutch_right, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->clutch_left_raw, 2u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->clutch_left_raw, 6u, 0xc0u);
    dst_p[5] |= pack_right_shift_u16(src_p->clutch_right_raw, 4u, 0x3fu);
    dst_p[6] |= pack_left_shift_u16(src_p->clutch_right_raw, 4u, 0xf0u);

    return (7);
}

int swc_clutch_unpack(
    struct swc_clutch_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->clutch_left = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->clutch_left |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->clutch_right = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->clutch_right |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->clutch_left_raw = unpack_left_shift_u16(src_p[4], 2u, 0xffu);
    dst_p->clutch_left_raw |= unpack_right_shift_u16(src_p[5], 6u, 0xc0u);
    dst_p->clutch_right_raw = unpack_left_shift_u16(src_p[5], 4u, 0x3fu);
    dst_p->clutch_right_raw |= unpack_right_shift_u16(src_p[6], 4u, 0xf0u);

    return (0);
}

int swc_clutch_init(struct swc_clutch_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct swc_clutch_t));

    return 0;
}

uint16_t swc_clutch_clutch_left_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double swc_clutch_clutch_left_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool swc_clutch_clutch_left_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t swc_clutch_clutch_right_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double swc_clutch_clutch_right_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool swc_clutch_clutch_right_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t swc_clutch_clutch_left_raw_encode(double value)
{
    return (uint16_t)(value);
}

double swc_clutch_clutch_left_raw_decode(uint16_t value)
{
    return ((double)value);
}

bool swc_clutch_clutch_left_raw_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t swc_clutch_clutch_right_raw_encode(double value)
{
    return (uint16_t)(value);
}

double swc_clutch_clutch_right_raw_decode(uint16_t value)
{
    return ((double)value);
}

bool swc_clutch_clutch_right_raw_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}
