/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 40.0.0 Thu Jul 31 17:23:20 2025.
 */

#ifndef TCS_H
#define TCS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define TCS_STATUS_FRAME_ID (0x1022u)
#define TCS_AUTO_SHIFT_RPM_FRAME_ID (0x1023u)
#define TCS_SERVO_FRAME_ID (0x1020u)
#define TCS_SETTINGS_FRAME_ID (0x1021u)

/* Frame lengths in bytes. */
#define TCS_STATUS_LENGTH (2u)
#define TCS_AUTO_SHIFT_RPM_LENGTH (8u)
#define TCS_SERVO_LENGTH (4u)
#define TCS_SETTINGS_LENGTH (8u)

/* Extended or standard frame types. */
#define TCS_STATUS_IS_EXTENDED (1)
#define TCS_AUTO_SHIFT_RPM_IS_EXTENDED (1)
#define TCS_SERVO_IS_EXTENDED (1)
#define TCS_SETTINGS_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */
#define TCS_AUTO_SHIFT_RPM_CYCLE_TIME_MS (1000u)
#define TCS_SERVO_CYCLE_TIME_MS (10u)
#define TCS_SETTINGS_CYCLE_TIME_MS (200u)

/* Signal choices. */


/* Frame Names. */
#define TCS_STATUS_NAME "status"
#define TCS_AUTO_SHIFT_RPM_NAME "auto_shift_rpm"
#define TCS_SERVO_NAME "servo"
#define TCS_SETTINGS_NAME "settings"

/* Signal Names. */
#define TCS_STATUS_OVER_REV_NAME "over_rev"
#define TCS_AUTO_SHIFT_RPM_AUTO_SHIFT_RPM_1_NAME "auto_shift_rpm_1"
#define TCS_AUTO_SHIFT_RPM_AUTO_SHIFT_RPM_2_NAME "auto_shift_rpm_2"
#define TCS_AUTO_SHIFT_RPM_AUTO_SHIFT_RPM_3_NAME "auto_shift_rpm_3"
#define TCS_AUTO_SHIFT_RPM_AUTO_SHIFT_RPM_4_NAME "auto_shift_rpm_4"
#define TCS_AUTO_SHIFT_RPM_AUTO_SHIFT_RPM_5_NAME "auto_shift_rpm_5"
#define TCS_SERVO_SERVO_PERCENTAGE_NAME "servo_percentage"
#define TCS_SERVO_SERVO_POSITION_NAME "servo_position"
#define TCS_SETTINGS_START_POINT_NAME "start_point"
#define TCS_SETTINGS_END_POINT_NAME "end_point"
#define TCS_SETTINGS_FRICTION_POINT_NAME "friction_point"
#define TCS_SETTINGS_AUTO_SHIFT_NAME "auto_shift"
#define TCS_SETTINGS_SERVO_POSITION_NAME "servo_position"
#define TCS_SETTINGS_SET_START_POINT_NAME "set_start_point"
#define TCS_SETTINGS_SET_END_POINT_NAME "set_end_point"
#define TCS_SETTINGS_SET_FRICTION_POINT_NAME "set_friction_point"
#define TCS_SETTINGS_SET_AUTO_SHIFT_NAME "set_auto_shift"
#define TCS_SETTINGS_SET_SERVO_POSITION_NAME "set_servo_position"
#define TCS_SETTINGS_RESET_EEPROM_NAME "reset_eeprom"

/**
 * Signals in message status.
 *
 * All signal values are as on the CAN bus.
 */
struct tcs_status_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t over_rev;
};

/**
 * Signals in message auto_shift_rpm.
 *
 * All signal values are as on the CAN bus.
 */
struct tcs_auto_shift_rpm_t {
    /**
     * Range: -1000..-898 (0..1023 RPM)
     * Scale: 10
     * Offset: 10000
     */
    uint16_t auto_shift_rpm_1;

    /**
     * Range: -1000..-898 (0..1023 RPM)
     * Scale: 10
     * Offset: 10000
     */
    uint16_t auto_shift_rpm_2;

    /**
     * Range: -1000..-898 (0..1023 RPM)
     * Scale: 10
     * Offset: 10000
     */
    uint16_t auto_shift_rpm_3;

    /**
     * Range: -1000..-898 (0..1023 RPM)
     * Scale: 10
     * Offset: 10000
     */
    uint16_t auto_shift_rpm_4;

    /**
     * Range: -1000..-898 (0..1023 RPM)
     * Scale: 10
     * Offset: 10000
     */
    uint16_t auto_shift_rpm_5;
};

/**
 * Signals in message servo.
 *
 * All signal values are as on the CAN bus.
 */
struct tcs_servo_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t servo_percentage;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t servo_position;
};

/**
 * Signals in message settings.
 *
 * All signal values are as on the CAN bus.
 */
struct tcs_settings_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t start_point;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t end_point;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t friction_point;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t auto_shift;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t servo_position;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t set_start_point;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t set_end_point;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t set_friction_point;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t set_auto_shift;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t set_servo_position;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t reset_eeprom;
};

/**
 * Pack message status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tcs_status_pack(
    uint8_t *dst_p,
    const struct tcs_status_t *src_p,
    size_t size);

/**
 * Unpack message status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tcs_status_unpack(
    struct tcs_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tcs_status_init(struct tcs_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tcs_status_over_rev_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_status_over_rev_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_status_over_rev_is_in_range(uint8_t value);

/**
 * Pack message auto_shift_rpm.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tcs_auto_shift_rpm_pack(
    uint8_t *dst_p,
    const struct tcs_auto_shift_rpm_t *src_p,
    size_t size);

/**
 * Unpack message auto_shift_rpm.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tcs_auto_shift_rpm_unpack(
    struct tcs_auto_shift_rpm_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from auto_shift_rpm.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tcs_auto_shift_rpm_init(struct tcs_auto_shift_rpm_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_auto_shift_rpm_auto_shift_rpm_1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_auto_shift_rpm_auto_shift_rpm_1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_auto_shift_rpm_auto_shift_rpm_1_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_auto_shift_rpm_auto_shift_rpm_2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_auto_shift_rpm_auto_shift_rpm_2_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_auto_shift_rpm_auto_shift_rpm_2_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_auto_shift_rpm_auto_shift_rpm_3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_auto_shift_rpm_auto_shift_rpm_3_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_auto_shift_rpm_auto_shift_rpm_3_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_auto_shift_rpm_auto_shift_rpm_4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_auto_shift_rpm_auto_shift_rpm_4_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_auto_shift_rpm_auto_shift_rpm_4_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_auto_shift_rpm_auto_shift_rpm_5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_auto_shift_rpm_auto_shift_rpm_5_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_auto_shift_rpm_auto_shift_rpm_5_is_in_range(uint16_t value);

/**
 * Pack message servo.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tcs_servo_pack(
    uint8_t *dst_p,
    const struct tcs_servo_t *src_p,
    size_t size);

/**
 * Unpack message servo.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tcs_servo_unpack(
    struct tcs_servo_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from servo.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tcs_servo_init(struct tcs_servo_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_servo_servo_percentage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_servo_servo_percentage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_servo_servo_percentage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_servo_servo_position_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_servo_servo_position_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_servo_servo_position_is_in_range(uint16_t value);

/**
 * Pack message settings.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tcs_settings_pack(
    uint8_t *dst_p,
    const struct tcs_settings_t *src_p,
    size_t size);

/**
 * Unpack message settings.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tcs_settings_unpack(
    struct tcs_settings_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from settings.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tcs_settings_init(struct tcs_settings_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_settings_start_point_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_start_point_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_start_point_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_settings_end_point_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_end_point_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_end_point_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_settings_friction_point_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_friction_point_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_friction_point_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tcs_settings_auto_shift_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_auto_shift_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_auto_shift_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tcs_settings_servo_position_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_servo_position_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_servo_position_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tcs_settings_set_start_point_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_set_start_point_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_set_start_point_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tcs_settings_set_end_point_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_set_end_point_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_set_end_point_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tcs_settings_set_friction_point_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_set_friction_point_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_set_friction_point_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tcs_settings_set_auto_shift_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_set_auto_shift_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_set_auto_shift_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tcs_settings_set_servo_position_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_set_servo_position_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_set_servo_position_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tcs_settings_reset_eeprom_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tcs_settings_reset_eeprom_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tcs_settings_reset_eeprom_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
