#pragma once
#include "swc.h"

#define swc_h SWC_H
#define swc_buttons_frame_id SWC_BUTTONS_FRAME_ID
#define swc_clutch_frame_id SWC_CLUTCH_FRAME_ID
#define swc_buttons_length SWC_BUTTONS_LENGTH
#define swc_clutch_length SWC_CLUTCH_LENGTH
#define swc_buttons_is_extended SWC_BUTTONS_IS_EXTENDED
#define swc_clutch_is_extended SWC_CLUTCH_IS_EXTENDED
#define swc_clutch_cycle_time_ms SWC_CLUTCH_CYCLE_TIME_MS
#define swc_buttons_shift_up_choice SWC_BUTTONS_SHIFT_UP_CHOICE
#define swc_buttons_shift_down_choice SWC_BUTTONS_SHIFT_DOWN_CHOICE
#define swc_buttons_encoder_pressed_choice SWC_BUTTONS_ENCODER_PRESSED_CHOICE
#define swc_buttons_encoder_clockwise_choice SWC_BUTTONS_ENCODER_CLOCKWISE_CHOICE
#define swc_buttons_encoder_counter_clockwise_choice SWC_BUTTONS_ENCODER_COUNTER_CLOCKWISE_CHOICE
#define swc_buttons_name SWC_BUTTONS_NAME
#define swc_clutch_name SWC_CLUTCH_NAME
#define swc_buttons_shift_name SWC_BUTTONS_SHIFT_NAME
#define swc_buttons_encoder_name SWC_BUTTONS_ENCODER_NAME
#define swc_clutch_clutch_left_name SWC_CLUTCH_CLUTCH_LEFT_NAME
#define swc_clutch_clutch_right_name SWC_CLUTCH_CLUTCH_RIGHT_NAME
#define swc_clutch_clutch_left_raw_name SWC_CLUTCH_CLUTCH_LEFT_RAW_NAME
#define swc_clutch_clutch_right_raw_name SWC_CLUTCH_CLUTCH_RIGHT_RAW_NAME
