/**
 * @file acc.h
 *
 * @brief This header file was generated by cantools version 41.1.1 Mon May  4 00:03:06 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef ACC_H
#define ACC_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define ACC_ACC_GROUP_3_FRAME_ID (0x1063u)
#define ACC_ACC_GROUP_1_FRAME_ID (0x1061u)
#define ACC_ACC_GROUP_2_FRAME_ID (0x1062u)
#define ACC_ACC_GROUP_0_FRAME_ID (0x1060u)

/* Frame lengths in bytes. */
#define ACC_ACC_GROUP_3_LENGTH (8u)
#define ACC_ACC_GROUP_1_LENGTH (8u)
#define ACC_ACC_GROUP_2_LENGTH (8u)
#define ACC_ACC_GROUP_0_LENGTH (8u)

/* Extended or standard frame types. */
#define ACC_ACC_GROUP_3_IS_EXTENDED (1)
#define ACC_ACC_GROUP_1_IS_EXTENDED (1)
#define ACC_ACC_GROUP_2_IS_EXTENDED (1)
#define ACC_ACC_GROUP_0_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */
#define ACC_ACC_GROUP_3_CYCLE_TIME_MS (4u)
#define ACC_ACC_GROUP_1_CYCLE_TIME_MS (4u)
#define ACC_ACC_GROUP_2_CYCLE_TIME_MS (4u)
#define ACC_ACC_GROUP_0_CYCLE_TIME_MS (4u)

/* Signal choices. */


/* Frame Names. */
#define ACC_ACC_GROUP_3_NAME "acc_group_3"
#define ACC_ACC_GROUP_1_NAME "acc_group_1"
#define ACC_ACC_GROUP_2_NAME "acc_group_2"
#define ACC_ACC_GROUP_0_NAME "acc_group_0"

/* Signal Names. */
#define ACC_ACC_GROUP_3_ACC_13_NAME "acc_13"
#define ACC_ACC_GROUP_3_ACC_14_NAME "acc_14"
#define ACC_ACC_GROUP_3_ACC_15_NAME "acc_15"
#define ACC_ACC_GROUP_3_ACC_16_NAME "acc_16"
#define ACC_ACC_GROUP_1_ACC_5_NAME "acc_5"
#define ACC_ACC_GROUP_1_ACC_6_NAME "acc_6"
#define ACC_ACC_GROUP_1_ACC_7_NAME "acc_7"
#define ACC_ACC_GROUP_1_ACC_8_NAME "acc_8"
#define ACC_ACC_GROUP_2_ACC_9_NAME "acc_9"
#define ACC_ACC_GROUP_2_ACC_10_NAME "acc_10"
#define ACC_ACC_GROUP_2_ACC_11_NAME "acc_11"
#define ACC_ACC_GROUP_2_ACC_12_NAME "acc_12"
#define ACC_ACC_GROUP_0_ACC_1_NAME "acc_1"
#define ACC_ACC_GROUP_0_ACC_2_NAME "acc_2"
#define ACC_ACC_GROUP_0_ACC_3_NAME "acc_3"
#define ACC_ACC_GROUP_0_ACC_4_NAME "acc_4"

/**
 * Signals in message acc_group_3.
 *
 * All signal values are as on the CAN bus.
 */
struct acc_acc_group_3_t {
    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_13;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_14;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_15;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_16;
};

/**
 * Signals in message acc_group_1.
 *
 * All signal values are as on the CAN bus.
 */
struct acc_acc_group_1_t {
    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_5;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_6;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_7;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_8;
};

/**
 * Signals in message acc_group_2.
 *
 * All signal values are as on the CAN bus.
 */
struct acc_acc_group_2_t {
    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_9;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_10;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_11;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_12;
};

/**
 * Signals in message acc_group_0.
 *
 * All signal values are as on the CAN bus.
 */
struct acc_acc_group_0_t {
    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_1;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_2;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_3;

    /**
     * Range: 0..65535 (0..5 V)
     * Scale: 7.62951e-05
     * Offset: 0
     */
    uint16_t acc_4;
};

/**
 * Pack message acc_group_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int acc_acc_group_3_pack(
    uint8_t *dst_p,
    const struct acc_acc_group_3_t *src_p,
    size_t size);

/**
 * Unpack message acc_group_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int acc_acc_group_3_unpack(
    struct acc_acc_group_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from acc_group_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int acc_acc_group_3_init(struct acc_acc_group_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_3_acc_13_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_3_acc_13_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_3_acc_13_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_3_acc_14_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_3_acc_14_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_3_acc_14_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_3_acc_15_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_3_acc_15_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_3_acc_15_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_3_acc_16_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_3_acc_16_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_3_acc_16_is_in_range(uint16_t value);

/**
 * Pack message acc_group_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int acc_acc_group_1_pack(
    uint8_t *dst_p,
    const struct acc_acc_group_1_t *src_p,
    size_t size);

/**
 * Unpack message acc_group_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int acc_acc_group_1_unpack(
    struct acc_acc_group_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from acc_group_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int acc_acc_group_1_init(struct acc_acc_group_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_1_acc_5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_1_acc_5_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_1_acc_5_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_1_acc_6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_1_acc_6_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_1_acc_6_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_1_acc_7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_1_acc_7_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_1_acc_7_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_1_acc_8_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_1_acc_8_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_1_acc_8_is_in_range(uint16_t value);

/**
 * Pack message acc_group_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int acc_acc_group_2_pack(
    uint8_t *dst_p,
    const struct acc_acc_group_2_t *src_p,
    size_t size);

/**
 * Unpack message acc_group_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int acc_acc_group_2_unpack(
    struct acc_acc_group_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from acc_group_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int acc_acc_group_2_init(struct acc_acc_group_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_2_acc_9_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_2_acc_9_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_2_acc_9_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_2_acc_10_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_2_acc_10_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_2_acc_10_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_2_acc_11_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_2_acc_11_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_2_acc_11_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_2_acc_12_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_2_acc_12_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_2_acc_12_is_in_range(uint16_t value);

/**
 * Pack message acc_group_0.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int acc_acc_group_0_pack(
    uint8_t *dst_p,
    const struct acc_acc_group_0_t *src_p,
    size_t size);

/**
 * Unpack message acc_group_0.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int acc_acc_group_0_unpack(
    struct acc_acc_group_0_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from acc_group_0.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int acc_acc_group_0_init(struct acc_acc_group_0_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_0_acc_1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_0_acc_1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_0_acc_1_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_0_acc_2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_0_acc_2_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_0_acc_2_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_0_acc_3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_0_acc_3_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_0_acc_3_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t acc_acc_group_0_acc_4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double acc_acc_group_0_acc_4_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool acc_acc_group_0_acc_4_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
