/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 40.0.0 Thu Oct 16 11:41:41 2025.
 */

#include <string.h>

#include "acc.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int acc_adc1_b_pack(
    uint8_t *dst_p,
    const struct acc_adc1_b_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_right_shift_u16(src_p->channel_4, 4u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->channel_4, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->channel_5, 8u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->channel_5, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->channel_6, 4u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->channel_6, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->channel_7, 8u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->channel_7, 0u, 0xffu);

    return (6);
}

int acc_adc1_b_unpack(
    struct acc_adc1_b_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->channel_4 = unpack_left_shift_u16(src_p[0], 4u, 0xffu);
    dst_p->channel_4 |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->channel_5 = unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->channel_5 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->channel_6 = unpack_left_shift_u16(src_p[3], 4u, 0xffu);
    dst_p->channel_6 |= unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->channel_7 = unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->channel_7 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

int acc_adc1_b_init(struct acc_adc1_b_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct acc_adc1_b_t));

    return 0;
}

uint16_t acc_adc1_b_channel_4_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc1_b_channel_4_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc1_b_channel_4_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc1_b_channel_5_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc1_b_channel_5_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc1_b_channel_5_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc1_b_channel_6_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc1_b_channel_6_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc1_b_channel_6_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc1_b_channel_7_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc1_b_channel_7_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc1_b_channel_7_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int acc_adc0_b_pack(
    uint8_t *dst_p,
    const struct acc_adc0_b_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_right_shift_u16(src_p->channel_4, 4u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->channel_4, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->channel_5, 8u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->channel_5, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->channel_6, 4u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->channel_6, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->channel_7, 8u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->channel_7, 0u, 0xffu);

    return (6);
}

int acc_adc0_b_unpack(
    struct acc_adc0_b_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->channel_4 = unpack_left_shift_u16(src_p[0], 4u, 0xffu);
    dst_p->channel_4 |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->channel_5 = unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->channel_5 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->channel_6 = unpack_left_shift_u16(src_p[3], 4u, 0xffu);
    dst_p->channel_6 |= unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->channel_7 = unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->channel_7 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

int acc_adc0_b_init(struct acc_adc0_b_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct acc_adc0_b_t));

    return 0;
}

uint16_t acc_adc0_b_channel_4_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc0_b_channel_4_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc0_b_channel_4_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc0_b_channel_5_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc0_b_channel_5_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc0_b_channel_5_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc0_b_channel_6_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc0_b_channel_6_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc0_b_channel_6_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc0_b_channel_7_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc0_b_channel_7_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc0_b_channel_7_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int acc_adc1_a_pack(
    uint8_t *dst_p,
    const struct acc_adc1_a_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_right_shift_u16(src_p->channel_0, 4u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->channel_0, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->channel_1, 8u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->channel_1, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->channel_2, 4u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->channel_2, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->channel_3, 8u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->channel_3, 0u, 0xffu);

    return (6);
}

int acc_adc1_a_unpack(
    struct acc_adc1_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->channel_0 = unpack_left_shift_u16(src_p[0], 4u, 0xffu);
    dst_p->channel_0 |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->channel_1 = unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->channel_1 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->channel_2 = unpack_left_shift_u16(src_p[3], 4u, 0xffu);
    dst_p->channel_2 |= unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->channel_3 = unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->channel_3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

int acc_adc1_a_init(struct acc_adc1_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct acc_adc1_a_t));

    return 0;
}

uint16_t acc_adc1_a_channel_0_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc1_a_channel_0_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc1_a_channel_0_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc1_a_channel_1_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc1_a_channel_1_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc1_a_channel_1_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc1_a_channel_2_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc1_a_channel_2_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc1_a_channel_2_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc1_a_channel_3_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc1_a_channel_3_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc1_a_channel_3_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int acc_adc0_a_pack(
    uint8_t *dst_p,
    const struct acc_adc0_a_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_right_shift_u16(src_p->channel_0, 4u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->channel_0, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->channel_1, 8u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->channel_1, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->channel_2, 4u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->channel_2, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->channel_3, 8u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->channel_3, 0u, 0xffu);

    return (6);
}

int acc_adc0_a_unpack(
    struct acc_adc0_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->channel_0 = unpack_left_shift_u16(src_p[0], 4u, 0xffu);
    dst_p->channel_0 |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->channel_1 = unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->channel_1 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->channel_2 = unpack_left_shift_u16(src_p[3], 4u, 0xffu);
    dst_p->channel_2 |= unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->channel_3 = unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->channel_3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

int acc_adc0_a_init(struct acc_adc0_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct acc_adc0_a_t));

    return 0;
}

uint16_t acc_adc0_a_channel_0_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc0_a_channel_0_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc0_a_channel_0_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc0_a_channel_1_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc0_a_channel_1_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc0_a_channel_1_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc0_a_channel_2_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc0_a_channel_2_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc0_a_channel_2_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t acc_adc0_a_channel_3_encode(double value)
{
    return (uint16_t)(value);
}

double acc_adc0_a_channel_3_decode(uint16_t value)
{
    return ((double)value);
}

bool acc_adc0_a_channel_3_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}
