/**
 * @file acc.c
 *
 * @brief This source file was generated by cantools version 41.1.1 Mon May  4 00:03:06 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "acc.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int acc_acc_group_3_pack(
    uint8_t *dst_p,
    const struct acc_acc_group_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->acc_13, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->acc_13, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->acc_14, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->acc_14, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->acc_15, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->acc_15, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->acc_16, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->acc_16, 0u, 0xffu);

    return (8);
}

int acc_acc_group_3_unpack(
    struct acc_acc_group_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->acc_13 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->acc_13 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acc_14 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->acc_14 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acc_15 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->acc_15 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acc_16 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->acc_16 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int acc_acc_group_3_init(struct acc_acc_group_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct acc_acc_group_3_t));

    return 0;
}

uint16_t acc_acc_group_3_acc_13_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_3_acc_13_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_3_acc_13_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_3_acc_14_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_3_acc_14_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_3_acc_14_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_3_acc_15_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_3_acc_15_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_3_acc_15_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_3_acc_16_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_3_acc_16_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_3_acc_16_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int acc_acc_group_1_pack(
    uint8_t *dst_p,
    const struct acc_acc_group_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->acc_5, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->acc_5, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->acc_6, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->acc_6, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->acc_7, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->acc_7, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->acc_8, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->acc_8, 0u, 0xffu);

    return (8);
}

int acc_acc_group_1_unpack(
    struct acc_acc_group_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->acc_5 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->acc_5 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acc_6 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->acc_6 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acc_7 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->acc_7 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acc_8 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->acc_8 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int acc_acc_group_1_init(struct acc_acc_group_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct acc_acc_group_1_t));

    return 0;
}

uint16_t acc_acc_group_1_acc_5_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_1_acc_5_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_1_acc_5_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_1_acc_6_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_1_acc_6_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_1_acc_6_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_1_acc_7_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_1_acc_7_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_1_acc_7_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_1_acc_8_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_1_acc_8_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_1_acc_8_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int acc_acc_group_2_pack(
    uint8_t *dst_p,
    const struct acc_acc_group_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->acc_9, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->acc_9, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->acc_10, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->acc_10, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->acc_11, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->acc_11, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->acc_12, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->acc_12, 0u, 0xffu);

    return (8);
}

int acc_acc_group_2_unpack(
    struct acc_acc_group_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->acc_9 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->acc_9 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acc_10 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->acc_10 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acc_11 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->acc_11 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acc_12 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->acc_12 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int acc_acc_group_2_init(struct acc_acc_group_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct acc_acc_group_2_t));

    return 0;
}

uint16_t acc_acc_group_2_acc_9_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_2_acc_9_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_2_acc_9_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_2_acc_10_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_2_acc_10_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_2_acc_10_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_2_acc_11_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_2_acc_11_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_2_acc_11_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_2_acc_12_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_2_acc_12_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_2_acc_12_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int acc_acc_group_0_pack(
    uint8_t *dst_p,
    const struct acc_acc_group_0_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->acc_1, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->acc_1, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->acc_2, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->acc_2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->acc_3, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->acc_3, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->acc_4, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->acc_4, 0u, 0xffu);

    return (8);
}

int acc_acc_group_0_unpack(
    struct acc_acc_group_0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->acc_1 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->acc_1 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acc_2 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->acc_2 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acc_3 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->acc_3 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acc_4 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->acc_4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int acc_acc_group_0_init(struct acc_acc_group_0_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct acc_acc_group_0_t));

    return 0;
}

uint16_t acc_acc_group_0_acc_1_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_0_acc_1_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_0_acc_1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_0_acc_2_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_0_acc_2_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_0_acc_2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_0_acc_3_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_0_acc_3_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_0_acc_3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t acc_acc_group_0_acc_4_encode(double value)
{
    return (uint16_t)(value / 7.62951e-05);
}

double acc_acc_group_0_acc_4_decode(uint16_t value)
{
    return ((double)value * 7.62951e-05);
}

bool acc_acc_group_0_acc_4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
